'use client';
import {useEffect,useMemo,useState} from 'react';
import Shell from '@/components/Shell';
import {loadBoqData,type BoqRow} from '@/lib/boqData';
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN');
const qty=(n:number)=>Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:3});
const value=(r:BoqRow)=>typeof r.rate==='number'?r.rate*r.approvedQty:0;
type Row=BoqRow&{executedQty:number;_key:string};
type Scheme={key:string;lot:string;id:string|null;name:string;block:string;dpr:string;items:number;approvedQty:number;executedQty:number;approvedValue:number;executedValue:number};
export default function SchemesPage(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [lot,setLot]=useState('All Lots'),[block,setBlock]=useState('All Blocks'),[scheme,setScheme]=useState('All Schemes'),[item,setItem]=useState(''),[selected,setSelected]=useState<string|null>(null);
 useEffect(()=>{let live=true;(async()=>{try{const raw=await loadBoqData();let ex:Record<string,number>={};try{ex=JSON.parse(localStorage.getItem('projectos-execution-v2')||'{}')}catch{};const out=raw.map(r=>{const k=[r.lot,r.schemeId||'',r.schemeName,r.itemCode,r.itemDescription].join('|');return {...r,executedQty:Math.min(r.approvedQty,Math.max(0,Number(ex[k]||0))),_key:k}});if(live)setRows(out)}catch(e){if(live)setError(e instanceof Error?e.message:'Unable to load BOQ')}finally{if(live)setLoading(false)}})();return()=>{live=false}},[]);
 const lots=useMemo(()=>Array.from(new Set(rows.map(r=>r.lot))).sort(),[rows]);
 const blocks=useMemo(()=>Array.from(new Set(rows.filter(r=>lot==='All Lots'||r.lot===lot).map(r=>r.block).filter(Boolean))).sort(),[rows,lot]);
 const schemeOptions=useMemo(()=>Array.from(new Set(rows.filter(r=>(lot==='All Lots'||r.lot===lot)&&(block==='All Blocks'||r.block===block)).map(r=>r.schemeName))).sort(),[rows,lot,block]);
 const filtered=useMemo(()=>rows.filter(r=>(lot==='All Lots'||r.lot===lot)&&(block==='All Blocks'||r.block===block)&&(scheme==='All Schemes'||r.schemeName===scheme)&&(!item||[r.itemCode,r.itemDescription,r.unit,r.category,r.part].join(' ').toLowerCase().includes(item.toLowerCase()))),[rows,lot,block,scheme,item]);
 const schemes=useMemo<Scheme[]>(()=>{const m=new Map<string,Scheme>();for(const r of filtered){const key=[r.lot,r.schemeId||'',r.schemeName].join('|');const x=m.get(key)||{key,lot:r.lot,id:r.schemeId,name:r.schemeName,block:r.block,dpr:String(r.dprNo??'—'),items:0,approvedQty:0,executedQty:0,approvedValue:0,executedValue:0};x.items++;x.approvedQty+=r.approvedQty;x.executedQty+=r.executedQty;x.approvedValue+=value(r);x.executedValue+=r.executedQty*(typeof r.rate==='number'?r.rate:0);m.set(key,x)}return Array.from(m.values()).sort((a,b)=>b.approvedValue-a.approvedValue)},[filtered]);
 const current=schemes.find(s=>s.key===selected)||schemes[0]||null;
 const currentItems=useMemo(()=>current?filtered.filter(r=>[r.lot,r.schemeId||'',r.schemeName].join('|')===current.key):[],[filtered,current]);
 const totalApprovedQty=filtered.reduce((s,r)=>s+r.approvedQty,0),totalExecutedQty=filtered.reduce((s,r)=>s+r.executedQty,0),totalApprovedValue=filtered.reduce((s,r)=>s+value(r),0),totalExecutedValue=filtered.reduce((s,r)=>s+r.executedQty*(typeof r.rate==='number'?r.rate:0),0);
 const exportScheme=()=>{if(!current)return;const head=['Lot','Scheme ID','Scheme','Block','Item Code','Description','Unit','Rate','Approved Qty','Consumed Qty','Remaining Qty','Approved Value','Consumed Value','Remaining Value'];const body=currentItems.map(r=>{const rem=Math.max(0,r.approvedQty-r.executedQty);return [r.lot,r.schemeId||'',r.schemeName,r.block,r.itemCode,r.itemDescription.replace(/\n/g,' '),r.unit,r.rate??'',r.approvedQty,r.executedQty,rem,typeof r.rate==='number'?value(r):'',typeof r.rate==='number'?r.executedQty*r.rate:'',typeof r.rate==='number'?rem*r.rate:'']});const csv=[head,...body].map(a=>a.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=(current.name.replace(/[^a-z0-9]+/gi,'_')||'scheme')+'_consumption.csv';a.click();URL.revokeObjectURL(a.href)};
 if(loading)return <Shell><div className='content'><h1 className='title'>Schemes</h1><p className='muted'>Loading scheme, quantity and consumption data…</p></div></Shell>;
 if(error)return <Shell><div className='content'><h1 className='title'>Schemes</h1><div className='card'>{error}</div></div></Shell>;
 return <Shell><div className='content'>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h1 className='title'>Scheme Register & Consumption</h1><p className='muted'>Master/approved quantity → consumed/executed quantity → remaining balance.</p></div><span className='badge'>{schemes.length.toLocaleString('en-IN')} schemes</span></div>
  <div className='card' style={{marginTop:16}}><h3>Filters</h3><div className='toolbar' style={{display:'grid',gridTemplateColumns:'160px 190px 1fr 1.5fr',gap:10,marginTop:10}}><select className='input' value={lot} onChange={e=>{setLot(e.target.value);setBlock('All Blocks');setScheme('All Schemes');setSelected(null)}}><option>All Lots</option>{lots.map(x=><option key={x}>{x}</option>)}</select><select className='input' value={block} onChange={e=>{setBlock(e.target.value);setScheme('All Schemes');setSelected(null)}}><option>All Blocks</option>{blocks.map(x=><option key={x}>{x}</option>)}</select><select className='input' value={scheme} onChange={e=>{setScheme(e.target.value);setSelected(null)}}><option>All Schemes</option>{schemeOptions.map(x=><option key={x}>{x}</option>)}</select><input className='input' placeholder='Filter by item name, item code, unit, category or part…' value={item} onChange={e=>setItem(e.target.value)}/></div></div>
  <div className='grid grid4' style={{marginTop:16}}><div className='card'><div className='muted'>Schemes Available</div><div className='kpi'>{schemes.length.toLocaleString('en-IN')}</div></div><div className='card'><div className='muted'>Master / Approved Qty</div><div className='kpi'>{qty(totalApprovedQty)}</div><div className='muted'>Current filtered view</div></div><div className='card'><div className='muted'>Consumed / Executed Qty</div><div className='kpi'>{qty(totalExecutedQty)}</div><div className='muted'>{totalApprovedQty?((totalExecutedQty/totalApprovedQty)*100).toFixed(1):0}% consumed</div></div><div className='card'><div className='muted'>Remaining Qty</div><div className='kpi'>{qty(Math.max(0,totalApprovedQty-totalExecutedQty))}</div><div className='muted'>Approved − consumed</div></div></div>
  <div className='grid grid3' style={{marginTop:16}}><div className='card'><div className='muted'>Approved Amount</div><div className='kpi'>{money(totalApprovedValue)}</div></div><div className='card'><div className='muted'>Consumed Amount</div><div className='kpi'>{money(totalExecutedValue)}</div></div><div className='card'><div className='muted'>Remaining Amount</div><div className='kpi'>{money(Math.max(0,totalApprovedValue-totalExecutedValue))}</div></div></div>
  <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>Scheme summary</h3><table className='table'><thead><tr><th>Lot</th><th>Scheme ID</th><th>Scheme</th><th>Block</th><th>Items</th><th>Approved Qty</th><th>Consumed Qty</th><th>Remaining Qty</th><th>Approved Amount</th><th>Consumed Amount</th><th>Remaining Amount</th><th></th></tr></thead><tbody>{schemes.map(s=><tr key={s.key} style={{background:current?.key===s.key?'#f8fbff':undefined}}><td>{s.lot}</td><td>{s.id||'—'}</td><td><b>{s.name}</b></td><td>{s.block||'—'}</td><td>{s.items}</td><td>{qty(s.approvedQty)}</td><td>{qty(s.executedQty)}</td><td><b>{qty(Math.max(0,s.approvedQty-s.executedQty))}</b></td><td>{money(s.approvedValue)}</td><td>{money(s.executedValue)}</td><td>{money(Math.max(0,s.approvedValue-s.executedValue))}</td><td><button className='btn secondary' onClick={()=>setSelected(s.key)}>View Items</button></td></tr>)}</tbody></table></div>
  {current&&<div className='card' style={{marginTop:16,overflowX:'auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div><h3 style={{marginBottom:4}}>{current.name}</h3><p className='muted' style={{marginTop:0}}>{current.lot} · {current.block} · ID {current.id||'—'}</p></div><button className='btn' onClick={exportScheme}>Export Item Consumption</button></div><table className='table'><thead><tr><th>Item Code</th><th>Item / Description</th><th>Unit</th><th>Rate</th><th>Master / Approved</th><th>Consumed</th><th>Remaining</th><th>Approved Amount</th><th>Consumed Amount</th><th>Remaining Amount</th></tr></thead><tbody>{currentItems.map((r,i)=>{const rem=Math.max(0,r.approvedQty-r.executedQty);return <tr key={r.itemCode+'|'+i}><td><b>{r.itemCode}</b></td><td style={{minWidth:420,whiteSpace:'pre-wrap'}}>{r.itemDescription}</td><td>{r.unit}</td><td>{typeof r.rate==='number'?money(r.rate):r.rate||'—'}</td><td>{qty(r.approvedQty)}</td><td>{qty(r.executedQty)}</td><td><b>{qty(rem)}</b></td><td>{typeof r.rate==='number'?money(r.approvedQty*r.rate):'—'}</td><td>{typeof r.rate==='number'?money(r.executedQty*r.rate):'—'}</td><td>{typeof r.rate==='number'?money(rem*r.rate):'—'}</td></tr>})}</tbody></table></div>}
  <div className='card' style={{marginTop:16}}><b>How this works:</b> The master/approved BOQ is the baseline. Consumed means recorded execution from the current execution register. Remaining quantity is calculated as Approved − Consumed. Use the item-name filter to see that item across all matching schemes, or combine it with Lot, Block and Scheme.</div>
 </div></Shell>;
}
