'use client';
import {useEffect,useMemo,useState} from 'react';
import Shell from '@/components/Shell';
import {loadBoqData,type BoqRow} from '@/lib/boqData';

const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN');
const qty=(n:number)=>Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:3});
const value=(r:BoqRow)=>typeof r.rate==='number'?r.rate*r.approvedQty:0;
type Scheme={key:string;lot:string;id:string|null;name:string;block:string;dpr:string;items:number;value:number;qty:number;numericItems:number};

export default function SchemesPage(){
 const [rows,setRows]=useState<BoqRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [lot,setLot]=useState('All Lots'),[block,setBlock]=useState('All Blocks'),[search,setSearch]=useState(''),[selected,setSelected]=useState<string|null>(null);
 useEffect(()=>{loadBoqData().then(setRows).catch(e=>setError(e instanceof Error?e.message:'Unable to load BOQ')).finally(()=>setLoading(false))},[]);
 const lots=useMemo(()=>Array.from(new Set(rows.map(r=>r.lot))).sort(),[rows]);
 const blocks=useMemo(()=>Array.from(new Set(rows.filter(r=>lot==='All Lots'||r.lot===lot).map(r=>r.block).filter(Boolean))).sort(),[rows,lot]);
 const schemes=useMemo<Scheme[]>(()=>{const m=new Map<string,Scheme>();for(const r of rows){if(lot!=='All Lots'&&r.lot!==lot)continue;if(block!=='All Blocks'&&r.block!==block)continue;const key=[r.lot,r.schemeId||'',r.schemeName].join('|');const x=m.get(key)||{key,lot:r.lot,id:r.schemeId,name:r.schemeName,block:r.block,dpr:String(r.dprNo??'—'),items:0,value:0,qty:0,numericItems:0};x.items++;x.qty+=r.approvedQty;x.value+=value(r);if(typeof r.rate==='number')x.numericItems++;m.set(key,x)}return Array.from(m.values()).sort((a,b)=>b.value-a.value)},[rows,lot,block]);
 const filtered=useMemo(()=>schemes.filter(s=>!search||[s.name,s.id,s.block,s.lot,s.dpr].join(' ').toLowerCase().includes(search.toLowerCase())),[schemes,search]);
 const current=schemes.find(s=>s.key===selected)||filtered[0]||null;
 const items=useMemo(()=>current?rows.filter(r=>r.lot===current.lot&&r.schemeName===current.name&&(r.schemeId||'')===(current.id||'')):[],[rows,current]);
 const categories=useMemo(()=>{const m=new Map<string,number>();for(const r of items){const k=r.category||'Uncategorised';m.set(k,(m.get(k)||0)+value(r))}return Array.from(m.entries()).sort((a,b)=>b[1]-a[1])},[items]);
 const exportScheme=()=>{if(!current)return;const head=['Lot','Scheme ID','Scheme','Block','Item Code','Description','Unit','Rate','Approved Qty','Approved Value'];const body=items.map(r=>[r.lot,r.schemeId||'',r.schemeName,r.block,r.itemCode,r.itemDescription.replace(/\n/g,' '),r.unit,r.rate??'',r.approvedQty,typeof r.rate==='number'?value(r):'']);const csv=[head,...body].map(a=>a.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=(current.name.replace(/[^a-z0-9]+/gi,'_')||'scheme')+'_BOQ.csv';a.click();URL.revokeObjectURL(a.href)};
 if(loading)return <Shell><div className='content'><h1 className='title'>Schemes</h1><p className='muted'>Loading the linked Lot 3 and Lot 4 scheme register…</p></div></Shell>;
 if(error)return <Shell><div className='content'><h1 className='title'>Schemes</h1><div className='card'>{error}</div></div></Shell>;
 const total=filtered.reduce((s,x)=>s+x.value,0),itemsCount=filtered.reduce((s,x)=>s+x.items,0),numeric=filtered.reduce((s,x)=>s+x.numericItems,0);
 return <Shell><div className='content'>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h1 className='title'>Scheme Register</h1><p className='muted'>Project → Lot → Scheme → BOQ Items. Every scheme below is calculated from the same approved BOQ dataset.</p></div></div>
  <div className='grid grid4' style={{marginTop:18}}><div className='card'><div className='muted'>Visible Schemes</div><div className='kpi'>{filtered.length}</div></div><div className='card'><div className='muted'>BOQ Items</div><div className='kpi'>{itemsCount.toLocaleString('en-IN')}</div></div><div className='card'><div className='muted'>Approved Value</div><div className='kpi'>{money(total)}</div></div><div className='card'><div className='muted'>Priced Items</div><div className='kpi'>{numeric.toLocaleString('en-IN')}</div></div></div>
  <div className='card' style={{marginTop:16}}><div className='toolbar' style={{display:'grid',gridTemplateColumns:'180px 200px 1fr auto',gap:10}}><select className='input' value={lot} onChange={e=>{setLot(e.target.value);setBlock('All Blocks');setSelected(null)}}><option>All Lots</option>{lots.map(x=><option key={x}>{x}</option>)}</select><select className='input' value={block} onChange={e=>{setBlock(e.target.value);setSelected(null)}}><option>All Blocks</option>{blocks.map(x=><option key={x}>{x}</option>)}</select><input className='input' placeholder='Search scheme name, ID, block or DPR…' value={search} onChange={e=>setSearch(e.target.value)}/><span className='badge'>{filtered.length} schemes</span></div></div>
  <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>All schemes</h3><table className='table'><thead><tr><th>Lot</th><th>Scheme ID</th><th>Scheme Name</th><th>Block</th><th>DPR No.</th><th>Items</th><th>Approved Qty</th><th>Approved Value</th><th></th></tr></thead><tbody>{filtered.map(s=><tr key={s.key} style={{background:current?.key===s.key?'#f8fbff':undefined}}><td><span className='badge'>{s.lot}</span></td><td>{s.id||'—'}</td><td><b>{s.name}</b></td><td>{s.block||'—'}</td><td>{s.dpr}</td><td>{s.items}</td><td>{qty(s.qty)}</td><td><b>{money(s.value)}</b></td><td><button className='btn secondary' onClick={()=>setSelected(s.key)}>Open</button></td></tr>)}</tbody></table></div>
  {current&&<><div className='grid grid3' style={{marginTop:16}}><div className='card'><div className='muted'>Selected Scheme</div><h2 style={{margin:'7px 0 0',fontSize:20}}>{current.name}</h2><p className='muted'>{current.lot} · {current.block} · ID {current.id||'—'}</p></div><div className='card'><div className='muted'>Approved BOQ</div><div className='kpi'>{money(current.value)}</div><div className='muted'>{current.items} item rows</div></div><div className='card'><div className='muted'>Quantity</div><div className='kpi'>{qty(current.qty)}</div><button className='btn' style={{marginTop:8}} onClick={exportScheme}>Export scheme BOQ</button></div></div>
   <div className='grid grid3' style={{marginTop:16}}><div className='card' style={{gridColumn:'span 2'}}><h3>Approved value by category</h3>{categories.slice(0,8).map(([name,v])=><div key={name} style={{marginTop:13}}><div style={{display:'flex',justifyContent:'space-between',fontSize:13}}><span>{name}</span><b>{money(v)}</b></div><div style={{height:9,background:'#e5e7eb',borderRadius:99,marginTop:5}}><div style={{height:'100%',width:(current.value?Math.min(100,v/current.value*100):0)+'%',background:'#2563eb',borderRadius:99}}/></div></div>)}</div><div className='card'><h3>Scheme navigation</h3><p className='muted'>The selected scheme is the bridge to the next modules.</p><div style={{display:'grid',gap:8}}><a className='btn secondary' href='/boq'>BOQ & Reconciliation</a><a className='btn secondary' href='/execution'>Execution</a><a className='btn secondary' href='/measurements'>Measurements</a><a className='btn secondary' href='/bills'>RA Bills</a></div></div></div>
   <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>Complete BOQ — {current.name}</h3><table className='table'><thead><tr><th>Item Code</th><th>Description</th><th>Unit</th><th>Rate</th><th>Approved Qty</th><th>Approved Value</th><th>Category</th><th>Part</th></tr></thead><tbody>{items.map((r,i)=><tr key={r.itemCode+'|'+i}><td><b>{r.itemCode}</b></td><td style={{minWidth:420,whiteSpace:'pre-wrap'}}>{r.itemDescription}</td><td>{r.unit}</td><td>{typeof r.rate==='number'?money(r.rate):r.rate||'—'}</td><td>{qty(r.approvedQty)}</td><td>{typeof r.rate==='number'?money(value(r)):'—'}</td><td>{r.category||'—'}</td><td>{r.part||'—'}</td></tr>)}</tbody></table></div>
  </>}
 </div></Shell>;
}
