'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import Shell from '@/components/Shell';
import {loadBoqData,type BoqRow} from '@/lib/boqData';
const EXP='projectos-expenses-v1', PAY='projectos-payments-v1', BILL='projectos-ra-bills-v1', EXEC='projectos-execution-v2';
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN');
const pct=(n:number)=>`${Math.max(0,Math.min(100,n)).toFixed(1)}%`;
type Bill={id:string;lot:string;scheme:string;date:string;gross:number;grandTotal:number;status:string};
type Expense={lot:string;block:string;scheme:string;amount:number;tax:number;status:string;category:string};
type Payment={lot:string;scheme:string;billId:string;amount:number;status:string};
type Exec=Record<string,number>;
const key=(r:BoqRow)=>[r.lot,r.schemeId||'',r.schemeName,r.itemCode,r.itemDescription].join('|');
export default function FinancePage(){
 const [rows,setRows]=useState<BoqRow[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[bills,setBills]=useState<Bill[]>([]),[payments,setPayments]=useState<Payment[]>([]),[exec,setExec]=useState<Exec>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[lot,setLot]=useState('All Lots');
 useEffect(()=>{try{Promise.all([loadBoqData(),Promise.resolve(JSON.parse(localStorage.getItem(EXP)||'[]')),Promise.resolve(JSON.parse(localStorage.getItem(BILL)||'[]')),Promise.resolve(JSON.parse(localStorage.getItem(PAY)||'[]')),Promise.resolve(JSON.parse(localStorage.getItem(EXEC)||'{}'))]).then(([r,e,b,p,x])=>{setRows(r);setExpenses(e);setBills(b);setPayments(p);setExec(x)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load project finance')).finally(()=>setLoading(false))}catch(e){setError(e instanceof Error?e.message:'Unable to load project finance');setLoading(false)}},[]);
 const lots=useMemo(()=>Array.from(new Set(rows.map(r=>r.lot))).sort(),[rows]);
 const data=useMemo(()=>rows.filter(r=>lot==='All Lots'||r.lot===lot),[rows,lot]);
 const approved=data.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*r.approvedQty:0),0);
 const executed=data.reduce((s,r)=>{const n=Number(exec[key(r)]||0);return s+(typeof r.rate==='number'?r.rate*Math.min(r.approvedQty,n):0)},0);
 const billed=bills.filter(b=>lot==='All Lots'||b.lot===lot).reduce((s,b)=>s+Number(b.grandTotal||0),0);
 const paid=payments.filter(p=>(lot==='All Lots'||p.lot===lot)&&p.status==='Paid').reduce((s,p)=>s+Number(p.amount||0),0);
 const costs=expenses.filter(e=>lot==='All Lots'||e.lot===lot).reduce((s,e)=>s+Number(e.amount||0)+Number(e.tax||0),0);
 const unpaid=Math.max(0,billed-paid),balance=Math.max(0,approved-executed),margin=billed-costs;
 const schemeStats=useMemo(()=>{const m=new Map<string,{lot:string;name:string;approved:number;executed:number;billed:number;cost:number}>();data.forEach(r=>{const id=k(r);let s=m.get(id);if(!s){s={lot:r.lot,name:r.schemeName,approved:0,executed:0,billed:0,cost:0};m.set(id,s)}if(typeof r.rate==='number'){s.approved+=r.rate*r.approvedQty;s.executed+=r.rate*Math.min(r.approvedQty,Number(exec[key(r)]||0))}});bills.filter(b=>lot==='All Lots'||b.lot===lot).forEach(b=>{const s=[...m.values()].find(x=>x.name===b.scheme);if(s)s.billed+=Number(b.grandTotal||0)});expenses.filter(e=>lot==='All Lots'||e.lot===lot).forEach(e=>{const s=[...m.values()].find(x=>x.name===e.scheme);if(s)s.cost+=Number(e.amount||0)+Number(e.tax||0)});return [...new Map([...m.values()].map(x=>[x.lot+'|'+x.name,x])).values()].sort((a,b)=>b.approved-a.approved)},[data,bills,expenses,exec,lot]);
 const lotStats=useMemo(()=>lots.map(l=>{const rr=rows.filter(r=>r.lot===l);const a=rr.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*r.approvedQty:0),0);const x=rr.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*Math.min(r.approvedQty,Number(exec[key(r)]||0)):0),0);const c=expenses.filter(e=>e.lot===l).reduce((s,e)=>s+e.amount+e.tax,0);const b=bills.filter(v=>v.lot===l).reduce((s,v)=>s+v.grandTotal,0);return {l,a,x,b,c}}),[lots,rows,exec,expenses,bills]);
 if(loading)return <Shell><div className='content'><h1 className='title'>Project Finance</h1><p className='muted'>Loading integrated financial position…</p></div></Shell>;
 if(error)return <Shell><div className='content'><h1 className='title'>Project Finance error</h1><div className='card'>{error}</div></div></Shell>;
 return <Shell><div className='content'><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h1 className='title'>Project Finance</h1><p className='muted'>One financial control view connecting BOQ, execution, billing, payments and actual cost.</p></div><div className='toolbar'><select className='input' value={lot} onChange={e=>setLot(e.target.value)}><option>All Lots</option>{lots.map(l=><option key={l}>{l}</option>)}</select><Link className='btn secondary' href='/reports'>Reports</Link></div></div>
 <div className='grid grid4' style={{marginTop:18}}><div className='card'><div className='muted'>Approved value</div><div className='kpi'>{money(approved)}</div><small>{data.length} BOQ rows</small></div><div className='card'><div className='muted'>Executed value</div><div className='kpi'>{money(executed)}</div><small>{pct(approved?executed/approved*100:0)} physical value progress</small></div><div className='card'><div className='muted'>Billed value</div><div className='kpi'>{money(billed)}</div><small>Unsettled: {money(unpaid)}</small></div><div className='card'><div className='muted'>Actual cost</div><div className='kpi'>{money(costs)}</div><small>Paid: {money(paid)}</small></div></div>
 <div className='grid grid3' style={{marginTop:16}}><div className='card'><h3>Financial position</h3><div style={{marginTop:14}}><div className='muted'>Execution vs approved</div><div style={{height:10,background:'#e5e7eb',borderRadius:99,margin:'6px 0 14px'}}><div style={{height:'100%',width:pct(approved?executed/approved*100:0),background:'#2563eb',borderRadius:99}}/></div><div style={{display:'flex',justifyContent:'space-between'}}><span>Balance BOQ</span><b>{money(balance)}</b></div></div><div style={{marginTop:18}}><div className='muted'>Billed vs executed</div><div style={{height:10,background:'#e5e7eb',borderRadius:99,margin:'6px 0 14px'}}><div style={{height:'100%',width:pct(executed?billed/executed*100:0),background:'#7c3aed',borderRadius:99}}/></div><div style={{display:'flex',justifyContent:'space-between'}}><span>Billing coverage</span><b>{pct(executed?billed/executed*100:0)}</b></div></div></div><div className='card'><h3>Cost & margin</h3><div className='grid grid2' style={{marginTop:12}}><div><div className='muted'>Billed</div><b>{money(billed)}</b></div><div><div className='muted'>Actual cost</div><b>{money(costs)}</b></div></div><div style={{marginTop:22,padding:14,borderRadius:10,background:'#f3f4f6'}}><div className='muted'>Indicative gross margin</div><div className='kpi'>{money(margin)}</div><div className='muted'>{billed?pct(margin/billed*100):'0.0%'} of billed value</div></div><p className='muted' style={{marginTop:12}}>Margin is based only on expenses currently entered in ProjectOS. It is not an accounting profit until all costs and adjustments are captured.</p></div><div className='card'><h3>Cash collection</h3><div style={{marginTop:14}}><div className='muted'>Paid against billed</div><div className='kpi'>{pct(billed?paid/billed*100:0)}</div><div style={{height:10,background:'#e5e7eb',borderRadius:99,marginTop:8}}><div style={{height:'100%',width:pct(billed?paid/billed*100:0),background:'#16a34a',borderRadius:99}}/></div></div><div style={{marginTop:18}}><div className='muted'>Receivable</div><b>{money(unpaid)}</b></div><Link className='btn secondary' href='/payments' style={{display:'inline-block',marginTop:18}}>Open Payments</Link></div></div>
 <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>Lot financial comparison</h3><table className='table'><thead><tr><th>Lot</th><th>Approved</th><th>Executed</th><th>Billed</th><th>Cost</th><th>Margin</th><th>Execution %</th></tr></thead><tbody>{lotStats.map(s=><tr key={s.l}><td><b>{s.l}</b></td><td>{money(s.a)}</td><td>{money(s.x)}</td><td>{money(s.b)}</td><td>{money(s.c)}</td><td>{money(s.b-s.c)}</td><td>{pct(s.a?s.x/s.a*100:0)}</td></tr>)}</tbody></table></div>
 <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>Scheme financial control</h3><table className='table'><thead><tr><th>Lot</th><th>Scheme</th><th>Approved</th><th>Executed</th><th>Billed</th><th>Actual Cost</th><th>Margin</th><th>Progress</th></tr></thead><tbody>{schemeStats.slice(0,200).map(s=><tr key={s.lot+'|'+s.name}><td>{s.lot}</td><td><b>{s.name}</b></td><td>{money(s.approved)}</td><td>{money(s.executed)}</td><td>{money(s.billed)}</td><td>{money(s.cost)}</td><td>{money(s.billed-s.cost)}</td><td>{pct(s.approved?s.executed/s.approved*100:0)}</td></tr>)}</tbody></table></div>
 <div className='grid grid4' style={{marginTop:16}}><Link className='card' href='/boq'><h3>BOQ & Reconciliation</h3><p className='muted'>Approved baseline and quantity/rate control.</p></Link><Link className='card' href='/execution'><h3>Execution</h3><p className='muted'>Physical progress and executed value.</p></Link><Link className='card' href='/bills'><h3>RA Bills</h3><p className='muted'>Certified/current billing position.</p></Link><Link className='card' href='/expenses'><h3>Expenses</h3><p className='muted'>Actual project cost register.</p></Link></div>
 </div></Shell>;
}
