'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import Shell from '@/components/Shell';
import {loadBoqData,type BoqRow} from '@/lib/boqData';
const EXP='projectos-expenses-v1',PAY='projectos-payments-v1',BILL='projectos-ra-bills-v1',EXEC='projectos-execution-v2';
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN');
const pct=(n:number)=>`${Math.max(0,Math.min(100,n)).toFixed(1)}%`;
type Bill={id:string;lot:string;scheme:string;date:string;grandTotal:number};
type Expense={lot:string;block:string;scheme:string;amount:number;tax:number};
type Payment={lot:string;scheme:string;billId:string;amount:number;status:string};
type Exec=Record<string,number>;
const key=(r:BoqRow)=>[r.lot,r.schemeId||'',r.schemeName,r.itemCode,r.itemDescription].join('|');
const card={background:'#fff',border:'1px solid #e5e7eb',borderRadius:14,padding:20,boxShadow:'0 1px 2px rgba(0,0,0,.03)'};
function Bar({value,max=100}:{value:number;max?:number}){return <div style={{height:9,background:'#eef2f7',borderRadius:99,overflow:'hidden'}}><div style={{height:'100%',width:`${Math.max(0,Math.min(100,value/max*100))}%`,background:'#2563eb',borderRadius:99}}/></div>}
export default function FinancePage(){
 const [rows,setRows]=useState<BoqRow[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[bills,setBills]=useState<Bill[]>([]),[payments,setPayments]=useState<Payment[]>([]),[exec,setExec]=useState<Exec>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[lot,setLot]=useState('All Lots');
 useEffect(()=>{Promise.all([loadBoqData(),Promise.resolve(JSON.parse(localStorage.getItem(EXP)||'[]')),Promise.resolve(JSON.parse(localStorage.getItem(BILL)||'[]')),Promise.resolve(JSON.parse(localStorage.getItem(PAY)||'[]')),Promise.resolve(JSON.parse(localStorage.getItem(EXEC)||'{}'))]).then(([r,e,b,p,x])=>{setRows(r);setExpenses(e);setBills(b);setPayments(p);setExec(x)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load project finance')).finally(()=>setLoading(false))},[]);
 const lots=useMemo(()=>Array.from(new Set(rows.map(r=>r.lot))).sort(),[rows]);
 const data=useMemo(()=>rows.filter(r=>lot==='All Lots'||r.lot===lot),[rows,lot]);
 const approved=data.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*r.approvedQty:0),0);
 const executed=data.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*Math.min(r.approvedQty,Number(exec[key(r)]||0)):0),0);
 const billed=bills.filter(b=>lot==='All Lots'||b.lot===lot).reduce((s,b)=>s+Number(b.grandTotal||0),0);
 const paid=payments.filter(p=>(lot==='All Lots'||p.lot===lot)&&p.status==='Paid').reduce((s,p)=>s+Number(p.amount||0),0);
 const costs=expenses.filter(e=>lot==='All Lots'||e.lot===lot).reduce((s,e)=>s+Number(e.amount||0)+Number(e.tax||0),0);
 const receivable=Math.max(0,billed-paid),balance=Math.max(0,approved-executed),margin=billed-costs;
 const schemeStats=useMemo(()=>{const m=new Map<string,{lot:string;name:string;approved:number;executed:number;billed:number;cost:number}>();data.forEach(r=>{const id=r.lot+'|'+r.schemeName;const s=m.get(id)||{lot:r.lot,name:r.schemeName,approved:0,executed:0,billed:0,cost:0};if(typeof r.rate==='number'){s.approved+=r.rate*r.approvedQty;s.executed+=r.rate*Math.min(r.approvedQty,Number(exec[key(r)]||0))}m.set(id,s)});bills.filter(b=>lot==='All Lots'||b.lot===lot).forEach(b=>{const s=m.get(b.lot+'|'+b.scheme);if(s)s.billed+=Number(b.grandTotal||0)});expenses.filter(e=>lot==='All Lots'||e.lot===lot).forEach(e=>{const s=m.get(e.lot+'|'+e.scheme);if(s)s.cost+=Number(e.amount||0)+Number(e.tax||0)});return [...m.values()].sort((a,b)=>b.approved-a.approved)},[data,bills,expenses,exec,lot]);
 const lotStats=useMemo(()=>lots.map(l=>{const rr=rows.filter(r=>r.lot===l);const a=rr.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*r.approvedQty:0),0);const x=rr.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*Math.min(r.approvedQty,Number(exec[key(r)]||0)):0),0);const c=expenses.filter(e=>e.lot===l).reduce((s,e)=>s+e.amount+e.tax,0);const b=bills.filter(v=>v.lot===l).reduce((s,v)=>s+Number(v.grandTotal||0),0);return {l,a,x,b,c}}),[lots,rows,exec,expenses,bills]);
 const maxLot=Math.max(1,...lotStats.map(s=>s.a));
 if(loading)return <Shell><div className='content'><h1 className='title'>Project Finance</h1><p className='muted'>Loading integrated financial position…</p></div></Shell>;
 if(error)return <Shell><div className='content'><h1 className='title'>Project Finance</h1><div className='card'>{error}</div></div></Shell>;
 return <Shell><div className='content'>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:20,flexWrap:'wrap'}}><div><div className='muted' style={{fontSize:12,fontWeight:700,letterSpacing:'.08em',textTransform:'uppercase'}}>Financial Control</div><h1 className='title' style={{marginBottom:5}}>Project Finance</h1><p className='muted'>A single view of approved value, execution, billing, collections and actual cost.</p></div><div className='toolbar'><select className='input' value={lot} onChange={e=>setLot(e.target.value)}><option>All Lots</option>{lots.map(l=><option key={l}>{l}</option>)}</select><Link className='btn secondary' href='/reports'>Reports</Link></div></div>
  <div className='grid grid4' style={{marginTop:20}}>{[['Approved Value',approved,'Baseline'],['Executed Value',executed,pct(approved?executed/approved*100:0)+' progress'],['Billed Value',billed,money(receivable)+' receivable'],['Actual Cost',costs,money(paid)+' paid']].map(([label,value,note])=><div key={String(label)} style={card}><div className='muted' style={{fontSize:13}}>{label}</div><div className='kpi' style={{fontSize:26,margin:'7px 0'}}>{money(Number(value))}</div><div className='muted' style={{fontSize:12}}>{note}</div></div>)}</div>
  <div className='grid grid3' style={{marginTop:18}}>
   <div style={card}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h3 style={{margin:0}}>Project position</h3><span className='badge'>{lot}</span></div><div style={{marginTop:20}}><div style={{display:'flex',justifyContent:'space-between',fontSize:13}}><span>Executed / Approved</span><b>{pct(approved?executed/approved*100:0)}</b></div><Bar value={executed} max={approved||1}/><div style={{display:'flex',justifyContent:'space-between',marginTop:8,fontSize:12}}><span>{money(executed)}</span><span className='muted'>Balance {money(balance)}</span></div></div><div style={{marginTop:22}}><div style={{display:'flex',justifyContent:'space-between',fontSize:13}}><span>Billed / Executed</span><b>{pct(executed?billed/executed*100:0)}</b></div><Bar value={billed} max={executed||1}/><div style={{display:'flex',justifyContent:'space-between',marginTop:8,fontSize:12}}><span>{money(billed)}</span><span className='muted'>Unbilled {money(Math.max(0,executed-billed))}</span></div></div></div>
   <div style={card}><h3 style={{margin:'0 0 15px'}}>Cost & margin</h3><div className='grid grid2'><div><div className='muted'>Billed</div><div style={{fontSize:18,fontWeight:700,marginTop:4}}>{money(billed)}</div></div><div><div className='muted'>Actual cost</div><div style={{fontSize:18,fontWeight:700,marginTop:4}}>{money(costs)}</div></div></div><div style={{marginTop:18,padding:16,borderRadius:11,background:'#f8fafc',border:'1px solid #eef2f7'}}><div className='muted'>Indicative gross margin</div><div className='kpi' style={{fontSize:25,margin:'5px 0'}}>{money(margin)}</div><div className='muted'>{billed?pct(margin/billed*100):'0.0%'} of billed value</div></div><p className='muted' style={{fontSize:12,lineHeight:1.5,marginBottom:0}}>Uses only expenses currently entered in ProjectOS. This is a management indicator, not final accounting profit.</p></div>
   <div style={card}><h3 style={{margin:'0 0 15px'}}>Cash collection</h3><div className='kpi' style={{fontSize:30}}>{pct(billed?paid/billed*100:0)}</div><div className='muted' style={{margin:'3px 0 10px'}}>of recorded bills collected</div><Bar value={paid} max={billed||1}/><div style={{display:'flex',justifyContent:'space-between',marginTop:14,fontSize:13}}><span>Collected</span><b>{money(paid)}</b></div><div style={{display:'flex',justifyContent:'space-between',marginTop:8,fontSize:13}}><span>Receivable</span><b>{money(receivable)}</b></div><Link className='btn secondary' href='/payments' style={{display:'inline-block',marginTop:17}}>Open Payments</Link></div>
  </div>
  <div style={{...card,marginTop:18}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14}}><div><h3 style={{margin:0}}>Approved value by lot</h3><p className='muted' style={{margin:'4px 0 0',fontSize:12}}>Baseline comparison; bars are scaled to the largest lot.</p></div></div>{lotStats.map(s=><div key={s.l} style={{marginTop:15}}><div style={{display:'grid',gridTemplateColumns:'90px 1fr 130px',gap:12,alignItems:'center',fontSize:13}}><b>{s.l}</b><Bar value={s.a} max={maxLot}/><b style={{textAlign:'right'}}>{money(s.a)}</b></div></div>)}</div>
  <div style={{...card,marginTop:18,overflowX:'auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><div><h3 style={{margin:0}}>Lot financial control</h3><p className='muted' style={{margin:'4px 0 14px',fontSize:12}}>Every figure is calculated from the shared BOQ and transaction registers.</p></div></div><table className='table'><thead><tr><th>Lot</th><th>Approved</th><th>Executed</th><th>Execution</th><th>Billed</th><th>Actual Cost</th><th>Indicative Margin</th></tr></thead><tbody>{lotStats.map(s=><tr key={s.l}><td><b>{s.l}</b></td><td>{money(s.a)}</td><td>{money(s.x)}</td><td>{pct(s.a?s.x/s.a*100:0)}</td><td>{money(s.b)}</td><td>{money(s.c)}</td><td>{money(s.b-s.c)}</td></tr>)}</tbody></table></div>
  <div style={{...card,marginTop:18,overflowX:'auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><div><h3 style={{margin:0}}>Scheme financial control</h3><p className='muted' style={{margin:'4px 0 14px',fontSize:12}}>Drill-down view: Approved → Executed → Billed → Cost → Margin.</p></div></div><table className='table'><thead><tr><th>Lot</th><th>Scheme</th><th>Approved</th><th>Executed</th><th>Progress</th><th>Billed</th><th>Actual Cost</th><th>Margin</th></tr></thead><tbody>{schemeStats.slice(0,200).map(s=><tr key={s.lot+'|'+s.name}><td>{s.lot}</td><td style={{minWidth:230}}><b>{s.name}</b></td><td>{money(s.approved)}</td><td>{money(s.executed)}</td><td>{pct(s.approved?s.executed/s.approved*100:0)}</td><td>{money(s.billed)}</td><td>{money(s.cost)}</td><td>{money(s.billed-s.cost)}</td></tr>)}</tbody></table></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:14,marginTop:18}}>{[['BOQ','Approved baseline and reconciliation.','/boq'],['Execution','Physical progress and quantities.','/execution'],['RA Bills','Current billing position.','/bills'],['Expenses','Actual cost register.','/expenses']].map(([t,d,h])=><Link key={String(t)} href={String(h)} style={{...card,textDecoration:'none',color:'inherit'}}><h3 style={{margin:'0 0 5px'}}>{t}</h3><p className='muted' style={{margin:0,fontSize:12}}>{d}</p></Link>)}</div>
  <div className='muted' style={{fontSize:11,marginTop:14}}>Data note: non-numeric BOQ rate rows are excluded from value calculations rather than assigned an invented rate. Transaction data currently uses browser persistence until the production database layer is connected.</div>
 </div></Shell>;
}
