'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import Shell from '@/components/Shell';
import {loadBoqData,type BoqRow} from '@/lib/boqData';
const EX='projectos-execution-v2',ME='projectos-measurements-v1',BILL='projectos-ra-bills-v1',PAY='projectos-payments-v1',EXP='projectos-expenses-v1';
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN');
const pct=(n:number)=>`${Math.max(0,Math.min(100,n)).toFixed(1)}%`;
const key=(r:BoqRow)=>[r.lot,r.schemeId||'',r.schemeName,r.itemCode,r.itemDescription].join('|');
type Bill={id:string;date:string;lot:string;scheme:string;number:string;grandTotal:number;status:string};
type Expense={lot:string;block:string;scheme:string;amount:number;tax:number;category:string};
type Payment={lot:string;scheme:string;billId:string;amount:number;status:string};
const PALETTE={navy:'#17324d',blue:'#2563eb',teal:'#0f766e',green:'#15803d',amber:'#c47a08',red:'#c2410c',slate:'#64748b',line:'#e7edf3'};
function Bar({value,max,color=PALETTE.blue}:{value:number;max:number;color?:string}){const width=max?Math.max(0,Math.min(100,value/max*100)):0;return <div style={{height:9,background:'#eef2f6',borderRadius:99,overflow:'hidden'}}><div style={{height:'100%',width:`${width}%`,background:color,borderRadius:99}}/></div>}
function Donut({parts}:{parts:{label:string;value:number;color:string}[]}){const total=parts.reduce((s,p)=>s+p.value,0)||1;let acc=0;const stops=parts.map(p=>{const a=acc/total*360;acc+=p.value;return `${p.color} ${a}deg ${acc/total*360}deg`}).join(',');return <div style={{width:150,height:150,borderRadius:'50%',background:`conic-gradient(${stops})`,display:'grid',placeItems:'center',flexShrink:0}}><div style={{width:94,height:94,borderRadius:'50%',background:'#fff',display:'grid',placeItems:'center',textAlign:'center'}}><b>{money(total)}</b></div></div>}
export default function ReportsPage(){
 const [rows,setRows]=useState<BoqRow[]>([]),[exec,setExec]=useState<Record<string,number>>({}),[meas,setMeas]=useState<Record<string,number>>({}),[bills,setBills]=useState<Bill[]>([]),[payments,setPayments]=useState<Payment[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[lot,setLot]=useState('All Lots'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{Promise.all([loadBoqData(),Promise.resolve(JSON.parse(localStorage.getItem(EX)||'{}')),Promise.resolve(JSON.parse(localStorage.getItem(ME)||'{}')),Promise.resolve(JSON.parse(localStorage.getItem(BILL)||'[]')),Promise.resolve(JSON.parse(localStorage.getItem(PAY)||'[]')),Promise.resolve(JSON.parse(localStorage.getItem(EXP)||'[]'))]).then(([r,x,m,b,p,e])=>{setRows(r);setExec(x);setMeas(m);setBills(b);setPayments(p);setExpenses(e)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load reports')).finally(()=>setLoading(false))},[]);
 const data=useMemo(()=>rows.filter(r=>lot==='All Lots'||r.lot===lot),[rows,lot]);
 const lots=useMemo(()=>Array.from(new Set(rows.map(r=>r.lot))).sort(),[rows]);
 const approved=data.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*r.approvedQty:0),0);
 const executed=data.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*Math.min(r.approvedQty,Number(exec[key(r)]||0)):0),0);
 const measured=data.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*Math.min(Math.min(r.approvedQty,Number(exec[key(r)]||0)),Number(meas[key(r)]||0)):0),0);
 const billed=bills.filter(b=>lot==='All Lots'||b.lot===lot).reduce((s,b)=>s+Number(b.grandTotal||0),0);
 const paid=payments.filter(p=>(lot==='All Lots'||p.lot===lot)&&p.status==='Paid').reduce((s,p)=>s+Number(p.amount||0),0);
 const cost=expenses.filter(e=>lot==='All Lots'||e.lot===lot).reduce((s,e)=>s+Number(e.amount||0)+Number(e.tax||0),0);
 const schemes=useMemo(()=>{const m=new Map<string,{name:string;lot:string;approved:number;executed:number;progress:number}>();data.forEach(r=>{const id=r.lot+'|'+r.schemeName;const s=m.get(id)||{name:r.schemeName,lot:r.lot,approved:0,executed:0,progress:0};if(typeof r.rate==='number'){s.approved+=r.rate*r.approvedQty;s.executed+=r.rate*Math.min(r.approvedQty,Number(exec[key(r)]||0))}m.set(id,s)});return [...m.values()].map(s=>({...s,progress:s.approved?s.executed/s.approved*100:0})).sort((a,b)=>b.approved-a.approved)},[data,exec]);
 const lotStats=useMemo(()=>lots.map(l=>{const rr=rows.filter(r=>r.lot===l);const a=rr.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*r.approvedQty:0),0);const x=rr.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*Math.min(r.approvedQty,Number(exec[key(r)]||0)):0),0);return {lot:l,approved:a,executed:x}}),[lots,rows,exec]);
 const categories=useMemo(()=>{const m=new Map<string,number>();expenses.filter(e=>lot==='All Lots'||e.lot===lot).forEach(e=>m.set(e.category,(m.get(e.category)||0)+Number(e.amount||0)+Number(e.tax||0)));const palette=[PALETTE.blue,PALETTE.teal,PALETTE.amber,PALETTE.red,PALETTE.navy];return [...m.entries()].sort((a,b)=>b[1]-a[1]).map(([label,value],i)=>({label,value,color:palette[i%palette.length]}))},[expenses,lot]);
 const billTrend=useMemo(()=>{const m=new Map<string,number>();bills.filter(b=>lot==='All Lots'||b.lot===lot).forEach(b=>{const date=b.date||'Undated';m.set(date,(m.get(date)||0)+Number(b.grandTotal||0))});let run=0;return [...m.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([date,value])=>{run+=value;return {date,value,cumulative:run}})},[bills,lot]);
 const exportReport=()=>{const lines:string[][]=[['Lot','Approved Value','Executed Value','Progress']];lotStats.forEach(s=>lines.push([s.lot,String(s.approved),String(s.executed),String(s.approved?s.executed/s.approved*100:0)]));const csv=lines.map(row=>row.map(v=>'"'+v.replaceAll('"','""')+'"').join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='ProjectOS_Management_Report.csv';a.click();URL.revokeObjectURL(url)};
 if(loading)return <Shell><div className='content'><h1 className='title'>Reports & Analytics</h1><p className='muted'>Loading management analytics…</p></div></Shell>;
 if(error)return <Shell><div className='content'><h1 className='title'>Reports & Analytics</h1><div className='card'>{error}</div></div></Shell>;
 return <Shell><div className='content'>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:18,flexWrap:'wrap'}}><div><div className='muted' style={{fontSize:12,fontWeight:800,letterSpacing:'.08em',textTransform:'uppercase'}}>Management Intelligence</div><h1 className='title' style={{marginBottom:5}}>Reports & Analytics</h1><p className='muted'>Clear project-control reporting from the same BOQ, execution, billing, payment and cost data.</p></div><div style={{display:'flex',gap:8}}><select className='input' style={{width:150}} value={lot} onChange={e=>setLot(e.target.value)}><option>All Lots</option>{lots.map(l=><option key={l}>{l}</option>)}</select><button className='btn' onClick={exportReport}>Export Report</button></div></div>
  <div className='grid grid4' style={{marginTop:20}}>{[['Approved',approved,PALETTE.navy],['Executed',executed,PALETTE.blue],['Measured',measured,PALETTE.teal],['Billed',billed,PALETTE.amber]].map(([l,v,c])=><div className='card' key={String(l)} style={{borderTop:`3px solid ${String(c)}`}}><div className='muted'>{l} value</div><div className='kpi'>{money(Number(v))}</div><div className='muted' style={{fontSize:12,marginTop:4}}>{l==='Executed'?pct(approved?executed/approved*100:0)+' of approved':l==='Measured'?pct(executed?measured/executed*100:0)+' of executed':l==='Billed'?pct(executed?billed/executed*100:0)+' of executed':'BOQ baseline'}</div></div>)}</div>
  <div className='grid grid2' style={{marginTop:18}}>
   <div className='card'><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h3 style={{margin:0}}>Lot progress comparison</h3><p className='muted' style={{fontSize:12,margin:'4px 0 16px'}}>Approved value against executed value.</p></div><span className='badge'>Value</span></div>{lotStats.map(s=><div key={s.lot} style={{marginBottom:17}}><div style={{display:'flex',justifyContent:'space-between',fontSize:13,marginBottom:6}}><b>{s.lot}</b><span>{pct(s.approved?s.executed/s.approved*100:0)}</span></div><Bar value={s.executed} max={s.approved||1} color={PALETTE.blue}/><div style={{fontSize:11,color:PALETTE.slate,marginTop:5}}>{money(s.executed)} executed / {money(s.approved)} approved</div></div>)}</div>
   <div className='card'><div><h3 style={{margin:0}}>Cost distribution</h3><p className='muted' style={{fontSize:12,margin:'4px 0 16px'}}>Entered actual cost by expense category.</p></div>{categories.length?<div style={{display:'flex',gap:25,alignItems:'center',flexWrap:'wrap'}}><Donut parts={categories}/><div style={{display:'grid',gap:9,flex:1,minWidth:180}}>{categories.map(c=><div key={c.label} style={{display:'flex',justifyContent:'space-between',gap:12,fontSize:13}}><span><i style={{display:'inline-block',width:9,height:9,borderRadius:3,background:c.color,marginRight:7}}/>{c.label}</span><b>{money(c.value)}</b></div>)}</div></div>:<p className='muted'>No expense data entered yet.</p>}</div>
  </div>
  <div className='grid grid2' style={{marginTop:18}}>
   <div className='card'><h3 style={{margin:0}}>Billing trend</h3><p className='muted' style={{fontSize:12,margin:'4px 0 15px'}}>Cumulative recorded RA billing by bill date.</p>{billTrend.length?<div style={{display:'grid',gap:8}}>{billTrend.map(p=><div key={p.date} style={{display:'grid',gridTemplateColumns:'88px 1fr 110px',gap:10,alignItems:'center',fontSize:12}}><span>{p.date}</span><Bar value={p.cumulative} max={billTrend[billTrend.length-1].cumulative||1} color={PALETTE.amber}/><b style={{textAlign:'right'}}>{money(p.cumulative)}</b></div>)}</div>:<div style={{padding:25,textAlign:'center',background:'#f8fafc',borderRadius:10}} className='muted'>Create RA bills to populate the billing trend.</div>}</div>
   <div className='card'><h3 style={{margin:0}}>Financial health</h3><p className='muted' style={{fontSize:12,margin:'4px 0 15px'}}>The key control ratios management should watch.</p>{[['Execution progress',approved?executed/approved*100:0,PALETTE.blue],['Measurement coverage',executed?measured/executed*100:0,PALETTE.teal],['Billing coverage',executed?billed/executed*100:0,PALETTE.amber],['Cash collection',billed?paid/billed*100:0,PALETTE.green]].map(([label,value,color])=><div key={String(label)} style={{marginBottom:15}}><div style={{display:'flex',justifyContent:'space-between',fontSize:13,marginBottom:6}}><span>{label}</span><b>{pct(Number(value))}</b></div><Bar value={Number(value)} max={100} color={String(color)}/></div>)}<div style={{display:'flex',justifyContent:'space-between',borderTop:`1px solid ${PALETTE.line}`,paddingTop:13,fontSize:13}}><span>Receivable</span><b>{money(Math.max(0,billed-paid))}</b></div></div>
  </div>
  <div className='card' style={{marginTop:18,overflowX:'auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h3 style={{margin:0}}>Top scheme performance</h3><p className='muted' style={{fontSize:12,margin:'4px 0 14px'}}>Largest approved schemes, ranked by physical value progress.</p></div><Link className='btn secondary' href='/schemes'>Scheme Register</Link></div><table className='table'><thead><tr><th>Lot</th><th>Scheme</th><th>Approved</th><th>Executed</th><th>Progress</th><th>Balance</th></tr></thead><tbody>{schemes.slice(0,15).map(s=><tr key={s.lot+'|'+s.name}><td>{s.lot}</td><td style={{minWidth:260}}><b>{s.name}</b></td><td>{money(s.approved)}</td><td>{money(s.executed)}</td><td style={{minWidth:150}}><div style={{display:'grid',gridTemplateColumns:'70px 1fr',gap:9,alignItems:'center'}}><b>{pct(s.progress)}</b><Bar value={s.progress} max={100} color={s.progress>=75?PALETTE.green:s.progress>=40?PALETTE.blue:PALETTE.amber}/></div></td><td>{money(Math.max(0,s.approved-s.executed))}</td></tr>)}</tbody></table></div>
  <div className='grid grid4' style={{marginTop:18}}>{[['Project Finance','Approved, executed, billed, cost and margin.','/finance'],['Execution','Quantity and physical progress register.','/execution'],['RA Bills','Billing and certification workflow.','/bills'],['Expenses','Actual cost and category analysis.','/expenses']].map(([t,d,h])=><Link key={String(t)} href={String(h)} className='card' style={{textDecoration:'none',color:'inherit'}}><h3 style={{margin:'0 0 5px'}}>{t}</h3><p className='muted' style={{fontSize:12,margin:0}}>{d}</p></Link>)}</div>
  <div className='muted' style={{fontSize:11,marginTop:14}}>Reporting note: charts use recorded ProjectOS transactions and the shared 2,116-row BOQ. Empty transaction series are intentionally shown as empty rather than estimated.</div>
 </div></Shell>;
}
