'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import Shell from '@/components/Shell';
import {loadBoqData,type BoqRow} from '@/lib/boqData';
const KEY='projectos-payments-v1';
const BILL_KEY='projectos-ra-bills-v1';
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN');
type Bill={id:string;lot:string;scheme:string;date:string;gross:number;grandTotal:number;status:string};
type Payment={id:string;date:string;billId:string;lot:string;scheme:string;payee:string;amount:number;mode:string;reference:string;status:'Pending'|'Paid'};
export default function PaymentsPage(){
 const [rows,setRows]=useState<BoqRow[]>([]),[bills,setBills]=useState<Bill[]>([]),[payments,setPayments]=useState<Payment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [lot,setLot]=useState('All Lots'),[q,setQ]=useState('');
 const [form,setForm]=useState({billId:'',payee:'',amount:'',mode:'Bank Transfer',reference:'',status:'Paid' as Payment['status']});
 useEffect(()=>{try{Promise.all([loadBoqData(),Promise.resolve(JSON.parse(localStorage.getItem(BILL_KEY)||'[]')),Promise.resolve(JSON.parse(localStorage.getItem(KEY)||'[]'))]).then(([r,b,p])=>{setRows(r);setBills(b);setPayments(p)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load payments')).finally(()=>setLoading(false))}catch(e){setError(e instanceof Error?e.message:'Unable to load payments');setLoading(false)}},[]);
 const lots=useMemo(()=>Array.from(new Set(rows.map(r=>r.lot))).sort(),[rows]);
 const filteredBills=useMemo(()=>bills.filter(b=>(lot==='All Lots'||b.lot===lot)&&(!q||`${b.scheme} ${b.id}`.toLowerCase().includes(q.toLowerCase()))),[bills,lot,q]);
 const totalBilled=useMemo(()=>bills.reduce((s,b)=>s+Number(b.grandTotal||0),0),[bills]);
 const totalPaid=useMemo(()=>payments.filter(p=>p.status==='Paid').reduce((s,p)=>s+p.amount,0),[payments]);
 const pending=useMemo(()=>payments.filter(p=>p.status==='Pending').reduce((s,p)=>s+p.amount,0),[payments]);
 const paidByBill=useMemo(()=>{const m:Record<string,number>={};payments.forEach(p=>m[p.billId]=(m[p.billId]||0)+(p.status==='Paid'?p.amount:0));return m},[payments]);
 const add=()=>{const b=bills.find(x=>x.id===form.billId);if(!b||!form.payee)return;const p:Payment={id:crypto.randomUUID(),date:new Date().toISOString().slice(0,10),billId:b.id,lot:b.lot,scheme:b.scheme,payee:form.payee,amount:Math.max(0,Number(form.amount)||0),mode:form.mode,reference:form.reference,status:form.status};const next=[p,...payments];setPayments(next);localStorage.setItem(KEY,JSON.stringify(next));setForm({billId:'',payee:'',amount:'',mode:'Bank Transfer',reference:'',status:'Paid'})};
 if(loading)return <Shell><div className='content'><h1 className='title'>Payments</h1><p className='muted'>Loading billing and payment registers…</p></div></Shell>;
 if(error)return <Shell><div className='content'><h1 className='title'>Payments error</h1><div className='card'>{error}</div></div></Shell>;
 return <Shell><div className='content'><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h1 className='title'>Payments</h1><p className='muted'>Track settlement of RA bills and maintain the billed → paid position.</p></div><Link className='btn secondary' href='/bills'>RA Bills</Link></div>
 <div className='grid grid4' style={{marginTop:18}}><div className='card'><div className='muted'>Total billed</div><div className='kpi'>{money(totalBilled)}</div></div><div className='card'><div className='muted'>Paid</div><div className='kpi'>{money(totalPaid)}</div></div><div className='card'><div className='muted'>Unsettled billed</div><div className='kpi'>{money(Math.max(0,totalBilled-totalPaid))}</div></div><div className='card'><div className='muted'>Pending payment entries</div><div className='kpi'>{money(pending)}</div></div></div>
 <div className='grid grid3' style={{marginTop:16}}><div className='card' style={{gridColumn:'span 2'}}><h3>Record payment</h3><div className='form'><label>RA Bill<select className='input' value={form.billId} onChange={e=>setForm({...form,billId:e.target.value})}><option value=''>Select bill</option>{filteredBills.map(b=><option key={b.id} value={b.id}>{b.id} · {b.scheme} · {money(b.grandTotal)}</option>)}</select></label><div className='grid grid3'><label>Payee / Contractor<input className='input' value={form.payee} onChange={e=>setForm({...form,payee:e.target.value})}/></label><label>Amount<input className='input' type='number' min='0' step='any' value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Payment Mode<select className='input' value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}><option>Bank Transfer</option><option>NEFT</option><option>RTGS</option><option>Cheque</option><option>Cash</option><option>Other</option></select></label></div><div className='grid grid3'><label>Reference / UTR<input className='input' value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label>Status<select className='input' value={form.status} onChange={e=>setForm({...form,status:e.target.value as Payment['status']})}><option>Paid</option><option>Pending</option></select></label></div><button className='btn' onClick={add}>Record Payment</button></div></div><div className='card'><h3>Settlement position</h3><div style={{height:12,background:'#e5e7eb',borderRadius:99,overflow:'hidden',margin:'18px 0'}}><div style={{height:'100%',width:(totalBilled?Math.min(100,totalPaid/totalBilled*100):0)+'%',background:'#16a34a'}}/></div><p><b>{totalBilled?((totalPaid/totalBilled)*100).toFixed(1):'0.0'}%</b> of recorded bills paid.</p><p className='muted'>Payments are linked to bill IDs so finance can reconcile each RA bill independently.</p></div></div>
 <div className='card' style={{marginTop:16}}><div className='toolbar'><select className='input' value={lot} onChange={e=>setLot(e.target.value)}><option>All Lots</option>{lots.map(x=><option key={x}>{x}</option>)}</select><input className='input' style={{minWidth:300}} placeholder='Search bill or scheme…' value={q} onChange={e=>setQ(e.target.value)}/></div></div>
 <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>Bill settlement register</h3><table className='table'><thead><tr><th>Bill</th><th>Lot</th><th>Scheme</th><th>Bill Date</th><th>Bill Amount</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>{filteredBills.map(b=>{const paid=paidByBill[b.id]||0;return <tr key={b.id}><td><b>{b.id}</b></td><td>{b.lot}</td><td>{b.scheme}</td><td>{b.date}</td><td>{money(b.grandTotal)}</td><td>{money(paid)}</td><td>{money(Math.max(0,b.grandTotal-paid))}</td><td><span className='badge'>{paid>=b.grandTotal?'Paid':paid?'Part Paid':'Unpaid'}</span></td></tr>})}</tbody></table>{!filteredBills.length&&<p className='muted'>No RA bills have been recorded yet. Create bills first from the RA Bills module.</p>}</div>
 <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>Payment register</h3><table className='table'><thead><tr><th>Date</th><th>Bill</th><th>Lot</th><th>Scheme</th><th>Payee</th><th>Amount</th><th>Mode</th><th>Reference</th><th>Status</th></tr></thead><tbody>{payments.filter(p=>lot==='All Lots'||p.lot===lot).map(p=><tr key={p.id}><td>{p.date}</td><td>{p.billId}</td><td>{p.lot}</td><td>{p.scheme}</td><td><b>{p.payee}</b></td><td>{money(p.amount)}</td><td>{p.mode}</td><td>{p.reference||'—'}</td><td><span className='badge'>{p.status}</span></td></tr>)}</tbody></table>{!payments.length&&<p className='muted'>No payments recorded yet.</p>}</div>
 </div></Shell>;
}
