'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import Shell from '@/components/Shell';
import {loadBoqData,type BoqRow} from '@/lib/boqData';
const EX='projectos-execution-v2',ME='projectos-measurements-v1';
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN');
const qty=(n:number)=>n.toLocaleString('en-IN',{maximumFractionDigits:3});
const rate=(r:BoqRow)=>typeof r.rate==='number'?r.rate:0;
const key=(r:BoqRow)=>[r.lot,r.schemeId||'',r.schemeName,r.itemCode,r.itemDescription].join('|');
function pct(a:number,b:number){return b?Math.min(100,a/b*100):0}
export default function MeasurementsPage(){
 const [rows,setRows]=useState<BoqRow[]>([]),[ex,setEx]=useState<Record<string,number>>({}),[meas,setMeas]=useState<Record<string,number>>({}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [lot,setLot]=useState('All Lots'),[block,setBlock]=useState('All Blocks'),[scheme,setScheme]=useState('All Schemes'),[q,setQ]=useState('');
 useEffect(()=>{try{Promise.all([loadBoqData(),Promise.resolve(JSON.parse(localStorage.getItem(EX)||'{}')),Promise.resolve(JSON.parse(localStorage.getItem(ME)||'{}'))]).then(([r,e,m])=>{setRows(r);setEx(e);setMeas(m)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load data')).finally(()=>setLoading(false))}catch(e){setError(e instanceof Error?e.message:'Unable to load data');setLoading(false)}},[]);
 const lots=useMemo(()=>Array.from(new Set(rows.map(r=>r.lot))).sort(),[rows]);
 const blocks=useMemo(()=>Array.from(new Set(rows.filter(r=>lot==='All Lots'||r.lot===lot).map(r=>r.block).filter(Boolean))).sort(),[rows,lot]);
 const schemes=useMemo(()=>Array.from(new Set(rows.filter(r=>(lot==='All Lots'||r.lot===lot)&&(block==='All Blocks'||r.block===block)).map(r=>r.schemeName))).sort(),[rows,lot,block]);
 const filtered=useMemo(()=>rows.filter(r=>(lot==='All Lots'||r.lot===lot)&&(block==='All Blocks'||r.block===block)&&(scheme==='All Schemes'||r.schemeName===scheme)&&(!q||Object.values(r).join(' ').toLowerCase().includes(q.toLowerCase()))),[rows,lot,block,scheme,q]);
 const executed=(r:BoqRow)=>Math.min(r.approvedQty,Math.max(0,Number(ex[key(r)]||0)));
 const measured=(r:BoqRow)=>Math.min(executed(r),Math.max(0,Number(meas[key(r)]||0)));
 const totals=useMemo(()=>filtered.reduce((a,r)=>{a.approved+=r.approvedQty;a.executed+=executed(r);a.measured+=measured(r);a.value+=rate(r)*measured(r);return a},{approved:0,executed:0,measured:0,value:0}),[filtered,ex,meas]);
 const save=(r:BoqRow,s:string)=>{const n=Math.min(executed(r),Math.max(0,Number(s)||0));const next={...meas,[key(r)]:n};setMeas(next);localStorage.setItem(ME,JSON.stringify(next))};
 const exportCsv=()=>{const data=[['Lot','Block','Scheme','Item Code','Description','Unit','Rate','Approved Qty','Executed Qty','Measured Qty','Unmeasured Executed Qty'],...filtered.map(r=>[r.lot,r.block,r.schemeName,r.itemCode,r.itemDescription.replace(/\n/g,' '),r.unit,r.rate??'',r.approvedQty,executed(r),measured(r),executed(r)-measured(r)])];const csv=data.map(a=>a.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='ProjectOS_Measurements.csv';a.click()};
 if(loading)return <Shell><div className='content'><h1 className='title'>Measurements</h1><p className='muted'>Loading BOQ, execution and measurement registers…</p></div></Shell>;
 if(error)return <Shell><div className='content'><h1 className='title'>Measurements error</h1><div className='card'>{error}</div></div></Shell>;
 return <Shell><div className='content'><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h1 className='title'>Measurement Book</h1><p className='muted'>Measurement is a controlled layer between site execution and billing. Measured quantity cannot exceed recorded execution.</p></div><div style={{display:'flex',gap:8}}><Link className='btn secondary' href='/execution'>Execution</Link><button className='btn' onClick={exportCsv}>Export CSV</button></div></div>
 <div className='grid grid4' style={{marginTop:18}}><div className='card'><div className='muted'>Approved Qty</div><div className='kpi'>{qty(totals.approved)}</div></div><div className='card'><div className='muted'>Executed Qty</div><div className='kpi'>{qty(totals.executed)}</div></div><div className='card'><div className='muted'>Measured Qty</div><div className='kpi'>{qty(totals.measured)}</div></div><div className='card'><div className='muted'>Measured Value</div><div className='kpi'>{money(totals.value)}</div></div></div>
 <div className='card' style={{marginTop:16}}><h3>Measurement chain</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:14,alignItems:'center'}}><div><div className='muted'>Approved</div><b>{qty(totals.approved)}</b></div><div><div className='muted'>Executed</div><b>{qty(totals.executed)}</b><div style={{height:8,background:'#e5e7eb',borderRadius:99,marginTop:5}}><div style={{height:'100%',width:pct(totals.executed,totals.approved)+'%',background:'#2563eb'}}/></div></div><div><div className='muted'>Measured</div><b>{qty(totals.measured)}</b><div style={{height:8,background:'#e5e7eb',borderRadius:99,marginTop:5}}><div style={{height:'100%',width:pct(totals.measured,totals.executed)+'%',background:'#2563eb'}}/></div></div></div><p className='muted' style={{marginTop:12}}>Measured value available for future billing: {money(totals.value)}</p></div>
 <div className='card' style={{marginTop:16}}><div className='toolbar'><select className='input' value={lot} onChange={e=>{setLot(e.target.value);setBlock('All Blocks');setScheme('All Schemes')}}><option>All Lots</option>{lots.map(x=><option key={x}>{x}</option>)}</select><select className='input' value={block} onChange={e=>{setBlock(e.target.value);setScheme('All Schemes')}}><option>All Blocks</option>{blocks.map(x=><option key={x}>{x}</option>)}</select><select className='input' value={scheme} onChange={e=>setScheme(e.target.value)}><option>All Schemes</option>{schemes.map(x=><option key={x}>{x}</option>)}</select><input className='input' style={{minWidth:280}} placeholder='Search item, scheme, code…' value={q} onChange={e=>setQ(e.target.value)}/><span className='badge'>{filtered.length.toLocaleString('en-IN')} rows</span></div></div>
 <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>Measurement register</h3><table className='table'><thead><tr><th>Lot</th><th>Scheme</th><th>Item</th><th>Description</th><th>Unit</th><th>Rate</th><th>Approved</th><th>Executed</th><th>Measured</th><th>Balance to measure</th><th>Measured Value</th><th>Save</th></tr></thead><tbody>{filtered.slice(0,2000).map(r=>{const e=executed(r),m=measured(r);return <tr key={key(r)}><td>{r.lot}</td><td>{r.schemeName}</td><td><b>{r.itemCode}</b></td><td style={{minWidth:340,whiteSpace:'pre-wrap'}}>{r.itemDescription}</td><td>{r.unit}</td><td>{typeof r.rate==='number'?money(r.rate):r.rate||'—'}</td><td>{qty(r.approvedQty)}</td><td>{qty(e)}</td><td><input className='input' style={{width:110}} type='number' min='0' max={e} step='any' value={m} onChange={ev=>save(r,ev.target.value)}/></td><td>{qty(e-m)}</td><td>{typeof r.rate==='number'?money(rate(r)*m):'—'}</td><td><span className='badge'>Saved</span></td></tr>})}</tbody></table>{filtered.length>2000&&<p className='muted'>Showing first 2,000 rows. Narrow the filters to continue.</p>}</div>
 <div className='card' style={{marginTop:16}}><h3>Next control point: RA Bills</h3><p className='muted'>Only measured quantities should flow into bill preparation. The billing module will keep previous bill, current bill and cumulative bill quantities separately.</p><Link className='btn' href='/bills'>Open RA Bills</Link></div>
 </div></Shell>;
}
