'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import Shell from '@/components/Shell';
import {loadBoqData,type BoqRow} from '@/lib/boqData';
const EX='projectos-execution-v2',ME='projectos-measurements-v1';
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN');
const qty=(n:number)=>n.toLocaleString('en-IN',{maximumFractionDigits:3});
const rate=(r:BoqRow)=>typeof r.rate==='number'?r.rate:0;
const key=(r:BoqRow)=>[r.lot,r.schemeId||'',r.schemeName,r.itemCode,r.itemDescription].join('|');
const pct=(a:number,b:number)=>b?Math.min(100,Math.max(0,a/b*100)):0;
export default function MeasurementsPage(){
 const [rows,setRows]=useState<BoqRow[]>([]),[ex,setEx]=useState<Record<string,number>>({}),[meas,setMeas]=useState<Record<string,number>>({}),[payPct,setPayPct]=useState<Record<string,number>>({}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [lot,setLot]=useState('All Lots'),[block,setBlock]=useState('All Blocks'),[scheme,setScheme]=useState('All Schemes'),[q,setQ]=useState('');
 useEffect(()=>{try{Promise.all([loadBoqData(),Promise.resolve(JSON.parse(localStorage.getItem(EX)||'{}')),Promise.resolve(JSON.parse(localStorage.getItem(ME)||'{}'))]).then(([r,e,m])=>{setRows(r);setEx(e);setMeas(m)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load data')).finally(()=>setLoading(false))}catch(e){setError(e instanceof Error?e.message:'Unable to load data');setLoading(false)}},[]);
 const lots=useMemo(()=>Array.from(new Set(rows.map(r=>r.lot))).sort(),[rows]);
 const blocks=useMemo(()=>Array.from(new Set(rows.filter(r=>lot==='All Lots'||r.lot===lot).map(r=>r.block).filter(Boolean))).sort(),[rows,lot]);
 const schemes=useMemo(()=>Array.from(new Set(rows.filter(r=>(lot==='All Lots'||r.lot===lot)&&(block==='All Blocks'||r.block===block)).map(r=>r.schemeName))).sort(),[rows,lot,block]);
 const filtered=useMemo(()=>rows.filter(r=>(lot==='All Lots'||r.lot===lot)&&(block==='All Blocks'||r.block===block)&&(scheme==='All Schemes'||r.schemeName===scheme)&&(!q||Object.values(r).join(' ').toLowerCase().includes(q.toLowerCase()))),[rows,lot,block,scheme,q]);
 const executed=(r:BoqRow)=>Math.min(r.approvedQty,Math.max(0,Number(ex[key(r)]||0)));
 const measured=(r:BoqRow)=>Math.min(executed(r),Math.max(0,Number(meas[key(r)]||0)));
 const paymentPercent=(r:BoqRow)=>Math.min(100,Math.max(0,Number(payPct[key(r)]||0)));
 const totals=useMemo(()=>filtered.reduce((a,r)=>{a.approved+=r.approvedQty;a.executed+=executed(r);a.measured+=measured(r);a.value+=rate(r)*measured(r);a.paidValue+=rate(r)*measured(r)*paymentPercent(r)/100;return a},{approved:0,executed:0,measured:0,value:0,paidValue:0}),[filtered,ex,meas,payPct]);
 const saveMeasurement=(r:BoqRow,s:string)=>{const n=Math.min(executed(r),Math.max(0,Number(s)||0));const next={...meas,[key(r)]:n};setMeas(next);localStorage.setItem(ME,JSON.stringify(next))};
 const savePayment=(r:BoqRow,s:string)=>{const n=Math.min(100,Math.max(0,Number(s)||0));const next={...payPct,[key(r)]:n};setPayPct(next);localStorage.setItem('projectos-measurement-payment-v1',JSON.stringify(next))};
 useEffect(()=>{try{setPayPct(JSON.parse(localStorage.getItem('projectos-measurement-payment-v1')||'{}'))}catch{setPayPct({})}},[]);
 const exportCsv=()=>{const data=[['Lot','Block','Scheme','Item Code','Description','Unit','Rate','Approved Qty','Executed Qty','Work Completed %','Measured Qty','Measurement % of Execution','Balance to Measure','Payment Done %','Measured Value','Payment Value'],...filtered.map(r=>{const e=executed(r),m=measured(r),wp=pct(e,r.approvedQty),mp=pct(m,e),pp=paymentPercent(r);return [r.lot,r.block,r.schemeName,r.itemCode,r.itemDescription.replace(/\n/g,' '),r.unit,r.rate??'',r.approvedQty,e,wp.toFixed(2),m,mp.toFixed(2),e-m,pp.toFixed(2),typeof r.rate==='number'?rate(r)*m:'',typeof r.rate==='number'?rate(r)*m*pp/100:'']})];const csv=data.map(a=>a.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='ProjectOS_Measurements.csv';a.click()};
 if(loading)return <Shell><div className='content'><h1 className='title'>Measurements</h1><p className='muted'>Loading BOQ, execution and measurement registers…</p></div></Shell>;
 if(error)return <Shell><div className='content'><h1 className='title'>Measurements error</h1><div className='card'>{error}</div></div></Shell>;
 return <Shell><div className='content'><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h1 className='title'>Measurement Book</h1><p className='muted'>Enter physical completion and verified measurement. Payment percentage is tracked separately so billing/payment never gets confused with site progress.</p></div><div style={{display:'flex',gap:8}}><Link className='btn secondary' href='/execution'>Execution</Link><button className='btn' onClick={exportCsv}>Export CSV</button></div></div>
 <div className='grid grid4' style={{marginTop:18}}><div className='card'><div className='muted'>Approved Qty</div><div className='kpi'>{qty(totals.approved)}</div></div><div className='card'><div className='muted'>Executed Qty</div><div className='kpi'>{qty(totals.executed)}</div></div><div className='card'><div className='muted'>Measured Qty</div><div className='kpi'>{qty(totals.measured)}</div></div><div className='card'><div className='muted'>Payment Value</div><div className='kpi'>{money(totals.paidValue)}</div></div></div>
 <div className='card' style={{marginTop:16}}><h3>Measurement & payment chain</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr 1fr',gap:14,alignItems:'center'}}><div><div className='muted'>Approved</div><b>{qty(totals.approved)}</b></div><div><div className='muted'>Executed</div><b>{qty(totals.executed)}</b><div style={{height:8,background:'#e5e7eb',borderRadius:99,marginTop:5}}><div style={{height:'100%',width:pct(totals.executed,totals.approved)+'%',background:'#2563eb'}}/></div></div><div><div className='muted'>Measured</div><b>{qty(totals.measured)}</b><div style={{height:8,background:'#e5e7eb',borderRadius:99,marginTop:5}}><div style={{height:'100%',width:pct(totals.measured,totals.executed)+'%',background:'#2563eb'}}/></div></div><div><div className='muted'>Payment</div><b>{money(totals.paidValue)}</b><div style={{height:8,background:'#e5e7eb',borderRadius:99,marginTop:5}}><div style={{height:'100%',width:pct(totals.paidValue,totals.value)+'%',background:'#2563eb'}}/></div></div></div><p className='muted' style={{marginTop:12}}>Measured value: {money(totals.value)} · Payment represented by entered payment percentage: {money(totals.paidValue)}</p></div>
 <div className='card' style={{marginTop:16}}><div className='toolbar'><select className='input' value={lot} onChange={e=>{setLot(e.target.value);setBlock('All Blocks');setScheme('All Schemes')}}><option>All Lots</option>{lots.map(x=><option key={x}>{x}</option>)}</select><select className='input' value={block} onChange={e=>{setBlock(e.target.value);setScheme('All Schemes')}}><option>All Blocks</option>{blocks.map(x=><option key={x}>{x}</option>)}</select><select className='input' value={scheme} onChange={e=>setScheme(e.target.value)}><option>All Schemes</option>{schemes.map(x=><option key={x}>{x}</option>)}</select><input className='input' style={{minWidth:280}} placeholder='Search item, scheme, code…' value={q} onChange={e=>setQ(e.target.value)}/><span className='badge'>{filtered.length.toLocaleString('en-IN')} rows</span></div></div>
 <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>Measurement register</h3><table className='table'><thead><tr><th>Lot</th><th>Scheme</th><th>Item</th><th>Description</th><th>Unit</th><th>Rate</th><th>Approved</th><th>Executed</th><th>Work Completed %</th><th>Measured</th><th>Measurement %</th><th>Balance</th><th>Payment Done %</th><th>Measured Value</th><th>Payment Value</th></tr></thead><tbody>{filtered.slice(0,2000).map(r=>{const e=executed(r),m=measured(r),wp=pct(e,r.approvedQty),mp=pct(m,e),pp=paymentPercent(r);return <tr key={key(r)}><td>{r.lot}</td><td>{r.schemeName}</td><td><b>{r.itemCode}</b></td><td style={{minWidth:340,whiteSpace:'pre-wrap'}}>{r.itemDescription}</td><td>{r.unit}</td><td>{r.itemCode==='1'||r.itemCode==='01'?money(1):typeof r.rate==='number'?money(r.rate):r.rate||'—'}</td><td>{qty(r.approvedQty)}</td><td>{qty(e)}</td><td><input className='input' style={{width:100}} type='number' min='0' max='100' step='0.01' value={wp.toFixed(2)} onChange={ev=>{const p=Math.min(100,Math.max(0,Number(ev.target.value)||0));const n=r.approvedQty*p/100;const next={...ex,[key(r)]:n};setEx(next);localStorage.setItem(EX,JSON.stringify(next))}}/></td><td><input className='input' style={{width:105}} type='number' min='0' max={e} step='any' value={m} onChange={ev=>saveMeasurement(r,ev.target.value)}/></td><td>{mp.toFixed(1)}%</td><td>{qty(e-m)}</td><td><input className='input' style={{width:100}} type='number' min='0' max='100' step='0.01' value={pp.toFixed(2)} onChange={ev=>savePayment(r,ev.target.value)}/></td><td>{typeof r.rate==='number'?money(rate(r)*m):'—'}</td><td>{typeof r.rate==='number'?money(rate(r)*m*pp/100):'—'}</td></tr>})}</tbody></table>{filtered.length>2000&&<p className='muted'>Showing first 2,000 rows. Narrow the filters to continue.</p>}</div>
 <div className='card' style={{marginTop:16}}><h3>How the breakup works</h3><p className='muted'>For each item, enter <b>Work Completed %</b> against approved quantity, then enter <b>Measured Qty</b> for the quantity verified by the engineer, and finally enter <b>Payment Done %</b> against the measured value. Item No. 1 is displayed with a rate of ₹1 so percentage-based breakup is easy to understand. These percentages are control inputs; formal RA Bills and Payments remain the financial records.</p><Link className='btn' href='/bills'>Open RA Bills</Link></div>
 </div></Shell>;
}
