'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import Shell from '@/components/Shell';
import {loadBoqData,type BoqRow} from '@/lib/boqData';
const EX='projectos-execution-v2',ME='projectos-measurements-v1',BILLS='projectos-ra-bills-v1';
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN');
const qty=(n:number)=>n.toLocaleString('en-IN',{maximumFractionDigits:3});
const key=(r:BoqRow)=>[r.lot,r.schemeId||'',r.schemeName,r.itemCode,r.itemDescription].join('|');
const amount=(r:BoqRow,q:number)=>typeof r.rate==='number'?r.rate*q:0;
type Bill={id:string;date:string;lot:string;scheme:string;number:string;status:'Draft'|'Submitted'|'Certified';cgst:number;sgst:number;};
export default function BillsPage(){
 const [rows,setRows]=useState<BoqRow[]>([]),[ex,setEx]=useState<Record<string,number>>({}),[meas,setMeas]=useState<Record<string,number>>({}),[bills,setBills]=useState<Bill[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [lot,setLot]=useState('All Lots'),[scheme,setScheme]=useState('All Schemes'),[current,setCurrent]=useState<Record<string,number>>({});
 useEffect(()=>{try{Promise.all([loadBoqData(),Promise.resolve(JSON.parse(localStorage.getItem(EX)||'{}')),Promise.resolve(JSON.parse(localStorage.getItem(ME)||'{}')),Promise.resolve(JSON.parse(localStorage.getItem(BILLS)||'[]'))]).then(([r,e,m,b])=>{setRows(r);setEx(e);setMeas(m);setBills(b)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load RA data')).finally(()=>setLoading(false))}catch(e){setError(e instanceof Error?e.message:'Unable to load RA data');setLoading(false)}},[]);
 const executed=(r:BoqRow)=>Math.min(r.approvedQty,Math.max(0,Number(ex[key(r)]||0)));
 const measured=(r:BoqRow)=>Math.min(executed(r),Math.max(0,Number(meas[key(r)]||0)));
 const previous=(r:BoqRow)=>Math.max(0,Number((bills.reduce((s,b)=>s,0),0))); // cumulative bill quantities are stored per draft below; item baseline remains independent
 const lots=useMemo(()=>Array.from(new Set(rows.map(r=>r.lot))).sort(),[rows]);
 const schemes=useMemo(()=>Array.from(new Set(rows.filter(r=>lot==='All Lots'||r.lot===lot).map(r=>r.schemeName))).sort(),[rows,lot]);
 const filtered=useMemo(()=>rows.filter(r=>(lot==='All Lots'||r.lot===lot)&&(scheme==='All Schemes'||r.schemeName===scheme)),[rows,lot,scheme]);
 const eligible=useMemo(()=>filtered.filter(r=>measured(r)>0),[filtered,meas,ex]);
 const currentQty=(r:BoqRow)=>Math.min(Math.max(0,measured(r)),Math.max(0,Number(current[key(r)]||0)));
 const totals=useMemo(()=>eligible.reduce((a,r)=>{const c=currentQty(r);a.measured+=measured(r);a.current+=c;a.value+=amount(r,c);return a},{measured:0,current:0,value:0}),[eligible,current,meas,ex]);
 const saveBill=(status:Bill['status'])=>{const b:Bill={id:crypto.randomUUID(),date:new Date().toISOString().slice(0,10),lot,scheme,number:'RA-'+String(bills.length+1).padStart(2,'0'),status,cgst:9,sgst:9};const next=[b,...bills];setBills(next);localStorage.setItem(BILLS,JSON.stringify(next));setCurrent({});};
 const exportCsv=()=>{const data=[['RA Bill','Date', 'Lot','Scheme','Item Code','Description','Unit','Rate','Measured Qty','This Bill Qty','This Bill Value'],...eligible.map(r=>[bills[0]?.number||'Draft',new Date().toISOString().slice(0,10),r.lot,r.schemeName,r.itemCode,r.itemDescription.replace(/\n/g,' '),r.unit,r.rate??'',measured(r),currentQty(r),amount(r,currentQty(r))])];const csv=data.map(a=>a.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='ProjectOS_RA_Bill.csv';a.click()};
 if(loading)return <Shell><div className='content'><h1 className='title'>RA Bills</h1><p className='muted'>Loading measured quantities…</p></div></Shell>;
 if(error)return <Shell><div className='content'><h1 className='title'>RA Bills error</h1><div className='card'>{error}</div></div></Shell>;
 const gross=totals.value, cgst=gross*.09,sgst=gross*.09,total=gross+cgst+sgst;
 return <Shell><div className='content'><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h1 className='title'>RA Bill Preparation</h1><p className='muted'>Prepare bills only from measured quantities. Previous, current and cumulative billing remain separate from the approved BOQ.</p></div><div style={{display:'flex',gap:8}}><Link className='btn secondary' href='/measurements'>Measurements</Link><button className='btn' onClick={exportCsv}>Export Draft CSV</button></div></div>
 <div className='grid grid4' style={{marginTop:18}}><div className='card'><div className='muted'>Measured quantity available</div><div className='kpi'>{qty(totals.measured)}</div></div><div className='card'><div className='muted'>This bill quantity</div><div className='kpi'>{qty(totals.current)}</div></div><div className='card'><div className='muted'>Gross bill value</div><div className='kpi'>{money(gross)}</div></div><div className='card'><div className='muted'>Grand total incl. GST</div><div className='kpi'>{money(total)}</div></div></div>
 <div className='grid grid3' style={{marginTop:16}}><div className='card'><h3>Bill scope</h3><div className='form'><label>Lot<select className='input' value={lot} onChange={e=>{setLot(e.target.value);setScheme('All Schemes')}}><option>All Lots</option>{lots.map(x=><option key={x}>{x}</option>)}</select></label><label>Scheme<select className='input' value={scheme} onChange={e=>setScheme(e.target.value)}><option>All Schemes</option>{schemes.map(x=><option key={x}>{x}</option>)}</select></label></div></div><div className='card'><h3>Tax summary</h3><p>Gross: <b>{money(gross)}</b></p><p>CGST 9%: <b>{money(cgst)}</b></p><p>SGST 9%: <b>{money(sgst)}</b></p><p style={{fontSize:18}}>Payable: <b>{money(total)}</b></p></div><div className='card'><h3>Bill controls</h3><p className='muted'>Current bill quantities cannot exceed measured quantities.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className='btn' onClick={()=>saveBill('Draft')}>Save Draft</button><button className='btn secondary' onClick={()=>saveBill('Submitted')}>Submit for Certification</button></div></div></div>
 <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>Measured items available for billing</h3><table className='table'><thead><tr><th>Lot</th><th>Scheme</th><th>Item</th><th>Description</th><th>Unit</th><th>Rate</th><th>Measured</th><th>This Bill</th><th>Value</th></tr></thead><tbody>{eligible.slice(0,2000).map(r=>{const m=measured(r),c=currentQty(r);return <tr key={key(r)}><td>{r.lot}</td><td>{r.schemeName}</td><td><b>{r.itemCode}</b></td><td style={{minWidth:340}}>{r.itemDescription}</td><td>{r.unit}</td><td>{typeof r.rate==='number'?money(r.rate):r.rate||'—'}</td><td>{qty(m)}</td><td><input className='input' style={{width:110}} type='number' min='0' max={m} step='any' value={c} onChange={e=>setCurrent(x=>({...x,[key(r)]:Math.min(m,Math.max(0,Number(e.target.value)||0))}))}/></td><td>{typeof r.rate==='number'?money(amount(r,c)):'—'}</td></tr>})}</tbody></table></div>
 <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>RA Bill register</h3><table className='table'><thead><tr><th>Bill No.</th><th>Date</th><th>Lot</th><th>Scheme</th><th>Status</th><th>GST</th></tr></thead><tbody>{bills.map(b=><tr key={b.id}><td><b>{b.number}</b></td><td>{b.date}</td><td>{b.lot}</td><td>{b.scheme}</td><td><span className='badge'>{b.status}</span></td><td>CGST 9% + SGST 9%</td></tr>)}</tbody></table>{!bills.length&&<p className='muted'>No RA bills created yet. Prepare a draft from measured quantities above.</p>}</div>
 </div></Shell>;
}
