'use client';
import { use, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import Shell from '@/components/Shell';
import { LOT3 } from '@/lib/lot3';
import { LOT4 } from '@/lib/lot4';
import { MASTER_SCHEMES } from '@/lib/master';

type Row={lot:string;schemeId:string;scheme:string;block:string;dpr:string;itemCode:string;description:string;unit:string;rate:number;approvedQty:number;executedQty:number;billedValue:number};
const KEY='projectos-execution-v1';
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN');
// The imported workbook datasets are structurally compatible with Row, but their
// literal inferred types differ because some source cells are nullable/readonly.
// Convert through unknown so TypeScript does not reject the runtime-compatible data.
const rows:Row[]=[...LOT3,...LOT4] as unknown as Row[];
const masterValue=MASTER_SCHEMES.reduce((s,x)=>s+x.estimatedValue,0);
const schemeCount=new Set(rows.map(r=>r.schemeId||r.scheme)).size;
function Stat({label,value,sub}:{label:string;value:string;sub?:string}){return <div className='card'><div className='muted'>{label}</div><div className='kpi'>{value}</div>{sub&&<div className='muted' style={{fontSize:12,marginTop:5}}>{sub}</div>}</div>}
export default function ModulePage({params}:{params:Promise<{slug?:string[]}>}){
 const {slug}=use(params),mod=slug?.join('/')||'dashboard';
 const [q,setQ]=useState(''),[lot,setLot]=useState('All'),[executed,setExecuted]=useState<Record<string,number>>({});
 useEffect(()=>{try{setExecuted(JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{}},[]);
 const data=useMemo(()=>rows.map((r,i)=>({...r,executedQty:executed[String(i)]??r.executedQty})),[executed]);
 const filtered=useMemo(()=>data.filter(r=>(lot==='All'||r.lot===lot)&&Object.values(r).join(' ').toLowerCase().includes(q.toLowerCase())),[data,lot,q]);
 const approved=data.reduce((s,r)=>s+r.approvedQty*r.rate,0),exec=data.reduce((s,r)=>s+r.executedQty*r.rate,0);
 const titles:Record<string,string>={dashboard:'HQ Control Dashboard',projects:'Projects',lots:'Lots & Blocks',schemes:'Schemes',boq:'BOQ & Reconciliation',execution:'Execution',measurements:'Measurements',bills:'RA Bills',purchases:'Purchases',expenses:'Expenses',payments:'Payments',finance:'Project Finance',reports:'Reports',documents:'Documents',issues:'Issues','admin/users':'Users & Roles',audit:'Audit Log'};
 const title=titles[mod]||'ProjectOS';
 const setQty=(row:Row,v:string)=>{const i=rows.indexOf(row),n=Math.max(0,Number(v)||0),next={...executed,[String(i)]:Math.min(row.approvedQty,n)};setExecuted(next);try{localStorage.setItem(KEY,JSON.stringify(next))}catch{}};
 const schemeRows=useMemo(()=>{const m=new Map<string,{id:string;name:string;block:string;value:number;executed:number}>();for(const r of data){const k=r.schemeId||r.scheme;const x=m.get(k)||{id:r.schemeId,name:r.scheme,block:r.block,value:0,executed:0};x.value+=r.approvedQty*r.rate;x.executed+=r.executedQty*r.rate;m.set(k,x)}return [...m.values()]},[data]);
 const lotRows=['Lot 3','Lot 4'].map(l=>{const a=data.filter(r=>r.lot===l);return {lot:l,value:a.reduce((s,r)=>s+r.approvedQty*r.rate,0),executed:a.reduce((s,r)=>s+r.executedQty*r.rate,0),schemes:new Set(a.map(r=>r.scheme)).size}});
 return <Shell><div className='content'>
 <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h1 className='title'>{title}</h1><p className='muted'>Master Project · Sant Kabir Nagar Rural Water Supply Project</p></div><Link className='btn' href='/dashboard'>Dashboard</Link></div>
 {(mod==='dashboard'||mod==='finance'||mod==='reports')&&<><div className='grid grid4' style={{marginTop:18}}><Stat label='Master Project Estimate' value={money(masterValue)} sub='Master scheme estimate'/><Stat label='Lot 3 Approved BOQ' value={money(lotRows[0].value)}/><Stat label='Lot 4 Approved BOQ' value={money(lotRows[1].value)}/><Stat label='Tracked Schemes' value={String(schemeCount)}/></div><div className='grid grid3' style={{marginTop:16}}><Stat label='Executed Value' value={money(exec)}/><Stat label='Balance Approved Value' value={money(Math.max(0,approved-exec))}/><Stat label='Execution Progress' value={approved?((exec/approved)*100).toFixed(2)+'%':'0%'}/></div></>}
 {(mod==='projects'||mod==='lots')&&<div className='card' style={{marginTop:16}}><h3>Lot control</h3><table className='table'><thead><tr><th>Lot</th><th>Schemes</th><th>Approved Value</th><th>Executed Value</th><th>Balance</th><th>Progress</th></tr></thead><tbody>{lotRows.map(x=><tr key={x.lot}><td><b>{x.lot}</b></td><td>{x.schemes}</td><td>{money(x.value)}</td><td>{money(x.executed)}</td><td>{money(Math.max(0,x.value-x.executed))}</td><td>{x.value?((x.executed/x.value)*100).toFixed(2):0}%</td></tr>)}</tbody></table></div>}
 {mod==='schemes'&&<div className='card' style={{marginTop:16,overflowX:'auto'}}><table className='table'><thead><tr><th>Scheme ID</th><th>Scheme</th><th>Block</th><th>Approved</th><th>Executed</th><th>Balance</th><th>Progress</th></tr></thead><tbody>{schemeRows.map(x=><tr key={x.id||x.name}><td>{x.id||'—'}</td><td>{x.name}</td><td>{x.block}</td><td>{money(x.value)}</td><td>{money(x.executed)}</td><td>{money(Math.max(0,x.value-x.executed))}</td><td>{x.value?((x.executed/x.value)*100).toFixed(2):0}%</td></tr>)}</tbody></table></div>}
 {mod==='boq'&&<div className='card' style={{marginTop:16}}><h3>Master vs Lot BOQ</h3><p className='muted'>Master estimate remains separate from lot-approved quantities. Reconciliation is a review layer; it never overwrites the original estimate.</p><div className='grid grid3'><Stat label='Master estimate' value={money(masterValue)}/><Stat label='Lot 3 + Lot 4 approved' value={money(lotRows[0].value+lotRows[1].value)}/><Stat label='Master minus lots' value={money(masterValue-lotRows[0].value-lotRows[1].value)}/></div></div>}
 {['boq','execution','measurements','bills','purchases','expenses','payments','reports'].includes(mod)&&<><div className='card' style={{marginTop:16,display:'flex',gap:10,flexWrap:'wrap'}}><input className='input' style={{maxWidth:500}} placeholder='Search scheme, item code, description, block…' value={q} onChange={e=>setQ(e.target.value)}/><select className='input' style={{maxWidth:150}} value={lot} onChange={e=>setLot(e.target.value)}><option>All</option><option>Lot 3</option><option>Lot 4</option></select><span className='badge'>{filtered.length.toLocaleString('en-IN')} rows</span></div><div className='card' style={{marginTop:16,overflowX:'auto'}}><table className='table'><thead><tr><th>Lot</th><th>Scheme ID</th><th>Block</th><th>Scheme</th><th>Item</th><th>Description</th><th>Unit</th><th>Rate</th><th>Approved Qty</th><th>Executed Qty</th><th>Balance</th><th>Approved Value</th></tr></thead><tbody>{filtered.slice(0,1000).map(r=><tr key={r.lot+'|'+r.schemeId+'|'+r.itemCode+'|'+r.description}><td>{r.lot}</td><td>{r.schemeId||'—'}</td><td>{r.block}</td><td>{r.scheme}</td><td>{r.itemCode}</td><td>{r.description}</td><td>{r.unit}</td><td>{money(r.rate)}</td><td>{r.approvedQty}</td><td>{mod==='execution'||mod==='measurements'?<input className='input' style={{width:105}} type='number' min='0' max={r.approvedQty} value={r.executedQty} onChange={e=>setQty(r,e.target.value)}/>:r.executedQty}</td><td>{Math.max(0,r.approvedQty-r.executedQty)}</td><td>{money(r.approvedQty*r.rate)}</td></tr>)}</tbody></table>{filtered.length>1000&&<p className='muted'>Showing 1,000 rows. Use search or lot filter to narrow the list.</p>}</div></>}
 {['documents','issues','admin/users','audit'].includes(mod)&&<div className='card' style={{marginTop:16}}><h3>{title}</h3><p className='muted'>This module is connected to the ProjectOS hierarchy. Production records will be linked to project, lot, block, scheme and item with user attribution and audit history.</p></div>}
 </div></Shell>}
