'use client';
import { use, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import Shell from '@/components/Shell';

type Row={lot:string;schemeId:string;scheme:string;block:string;dpr:string;itemCode:string;description:string;unit:string;rate:number;approvedQty:number;executedQty:number;billedValue:number};
const KEY='projectos-boq-v2';
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN');
const SEED:Row[]=[];
const MASTER_VALUE=94327925.91;
const LOT_TOTALS={"Lot 3":20141827,"Lot 4":74186099};
function Stat({label,value,sub}:{label:string;value:string;sub?:string}){return <div className='card'><div className='muted'>{label}</div><div className='kpi'>{value}</div>{sub&&<div className='muted' style={{fontSize:12,marginTop:5}}>{sub}</div>}</div>}
export default function ModulePage({params}:{params:Promise<{slug?:string[]}>}){
 const {slug}=use(params),mod=slug?.join('/')||'dashboard';
 const [q,setQ]=useState(''),[lot,setLot]=useState('All'),[rows,setRows]=useState<Row[]>(SEED),[executed,setExecuted]=useState<Record<string,number>>({});
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(saved)&&saved.length)setRows(saved)}catch{};try{setExecuted(JSON.parse(localStorage.getItem('projectos-execution-v1')||'{}'))}catch{}},[]);
 const data=useMemo(()=>rows.map((r,i)=>({...r,executedQty:executed[String(i)]??r.executedQty})),[rows,executed]);
 const filtered=useMemo(()=>data.filter(r=>(lot==='All'||r.lot===lot)&&Object.values(r).join(' ').toLowerCase().includes(q.toLowerCase())),[data,lot,q]);
 const approved=data.reduce((s,r)=>s+r.approvedQty*r.rate,0),exec=data.reduce((s,r)=>s+r.executedQty*r.rate,0);
 const titles:Record<string,string>={dashboard:'HQ Control Dashboard',projects:'Projects',lots:'Lots & Blocks',schemes:'Schemes',boq:'BOQ & Reconciliation',execution:'Execution',measurements:'Measurements',bills:'RA Bills',purchases:'Purchases',expenses:'Expenses',payments:'Payments',finance:'Project Finance',reports:'Reports',documents:'Documents',issues:'Issues','admin/users':'Users & Roles',audit:'Audit Log'};
 const title=titles[mod]||'ProjectOS';
 const setQty=(row:Row,v:string)=>{const i=rows.indexOf(row),n=Math.max(0,Number(v)||0),next={...executed,[String(i)]:Math.min(row.approvedQty,n)};setExecuted(next);try{localStorage.setItem('projectos-execution-v1',JSON.stringify(next))}catch{}};
 const lotRows=['Lot 3','Lot 4'].map(l=>{const a=data.filter(r=>r.lot===l);const value=a.length?a.reduce((s,r)=>s+r.approvedQty*r.rate,0):LOT_TOTALS[l as 'Lot 3'|'Lot 4'];const ex=a.reduce((s,r)=>s+r.executedQty*r.rate,0);return {lot:l,value,executed:ex,schemes:new Set(a.map(r=>r.scheme)).size}});
 return <Shell><div className='content'>
 <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h1 className='title'>{title}</h1><p className='muted'>Master Project · Sant Kabir Nagar Rural Water Supply Project</p></div><Link className='btn' href='/dashboard'>Dashboard</Link></div>
 {(mod==='dashboard'||mod==='finance'||mod==='reports')&&<><div className='grid grid4' style={{marginTop:18}}><Stat label='Master Project Estimate' value={money(MASTER_VALUE)} sub='Current imported master baseline'/><Stat label='Lot 3 Approved BOQ' value={money(lotRows[0].value)}/><Stat label='Lot 4 Approved BOQ' value={money(lotRows[1].value)}/><Stat label='Tracked Schemes' value={data.length?String(new Set(data.map(r=>r.schemeId||r.scheme)).size):'93'}/></div><div className='grid grid3' style={{marginTop:16}}><Stat label='Executed Value' value={money(exec)}/><Stat label='Balance Approved Value' value={money(Math.max(0,(lotRows[0].value+lotRows[1].value)-exec))}/><Stat label='Execution Progress' value={(lotRows[0].value+lotRows[1].value)?((exec/(lotRows[0].value+lotRows[1].value))*100).toFixed(2)+'%':'0%'}/></div></>}
 {(mod==='projects'||mod==='lots')&&<div className='card' style={{marginTop:16}}><h3>Lot control</h3><table className='table'><thead><tr><th>Lot</th><th>Schemes</th><th>Approved Value</th><th>Executed Value</th><th>Balance</th><th>Progress</th></tr></thead><tbody>{lotRows.map(x=><tr key={x.lot}><td><b>{x.lot}</b></td><td>{x.schemes||'—'}</td><td>{money(x.value)}</td><td>{money(x.executed)}</td><td>{money(Math.max(0,x.value-x.executed))}</td><td>{x.value?((x.executed/x.value)*100).toFixed(2):0}%</td></tr>)}</tbody></table></div>}
 {mod==='boq'&&<div className='card' style={{marginTop:16}}><h3>Master vs Lot BOQ</h3><p className='muted'>The master estimate and lot-approved BOQs remain separate baselines. Upload the BOQ workbook below to load row-level data into this browser session.</p><div className='grid grid3'><Stat label='Master estimate' value={money(MASTER_VALUE)}/><Stat label='Lot 3 + Lot 4 approved' value={money(LOT_TOTALS['Lot 3']+LOT_TOTALS['Lot 4'])}/><Stat label='Unallocated master value' value={money(MASTER_VALUE-LOT_TOTALS['Lot 3']-LOT_TOTALS['Lot 4'])}/></div></div>}
 {['boq','execution','measurements','bills','purchases','expenses','payments','reports'].includes(mod)&&<><div className='card' style={{marginTop:16,display:'flex',gap:10,flexWrap:'wrap'}}><input className='input' style={{maxWidth:500}} placeholder='Search scheme, item code, description, block…' value={q} onChange={e=>setQ(e.target.value)}/><select className='input' style={{maxWidth:150}} value={lot} onChange={e=>setLot(e.target.value)}><option>All</option><option>Lot 3</option><option>Lot 4</option></select><span className='badge'>{filtered.length.toLocaleString('en-IN')} rows</span></div>{data.length?<div className='card' style={{marginTop:16,overflowX:'auto'}}><table className='table'><thead><tr><th>Lot</th><th>Scheme ID</th><th>Block</th><th>Scheme</th><th>Item</th><th>Description</th><th>Unit</th><th>Rate</th><th>Approved Qty</th><th>Executed Qty</th><th>Balance</th><th>Approved Value</th></tr></thead><tbody>{filtered.slice(0,1000).map(r=><tr key={r.lot+'|'+r.schemeId+'|'+r.itemCode+'|'+r.description}><td>{r.lot}</td><td>{r.schemeId||'—'}</td><td>{r.block}</td><td>{r.scheme}</td><td>{r.itemCode}</td><td>{r.description}</td><td>{r.unit}</td><td>{money(r.rate)}</td><td>{r.approvedQty}</td><td>{mod==='execution'||mod==='measurements'?<input className='input' style={{width:105}} type='number' min='0' max={r.approvedQty} value={r.executedQty} onChange={e=>setQty(r,e.target.value)}/>:r.executedQty}</td><td>{Math.max(0,r.approvedQty-r.executedQty)}</td><td>{money(r.approvedQty*r.rate)}</td></tr>)}</tbody></table></div>:<div className='card' style={{marginTop:16}}><h3>No row-level BOQ loaded in this browser yet</h3><p className='muted'>Use the BOQ import workflow to load the Excel data. The current project-level Lot 3 and Lot 4 approved totals are already shown above.</p><Link className='btn' href='/boq'>Open BOQ import</Link></div>}</>}
 {['documents','issues','admin/users','audit'].includes(mod)&&<div className='card' style={{marginTop:16}}><h3>{title}</h3><p className='muted'>Production records will be linked to project, lot, block, scheme and item with user attribution and immutable audit history.</p></div>}
 </div></Shell>}
