'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import Shell from '@/components/Shell';
import {loadBoqData,type BoqRow} from '@/lib/boqData';
const KEY='projectos-expenses-v1';
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN');
const qty=(n:number)=>n.toLocaleString('en-IN',{maximumFractionDigits:3});
const k=(r:BoqRow)=>[r.lot,r.schemeId||'',r.schemeName,r.itemCode,r.itemDescription].join('|');
type Expense={id:string;date:string;lot:string;block:string;scheme:string;item:string;category:string;vendor:string;invoice:string;qty:number;rate:number;tax:number;amount:number;status:'Unpaid'|'Paid'};
export default function ExpensesPage(){
 const [rows,setRows]=useState<BoqRow[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [lot,setLot]=useState('All Lots'),[block,setBlock]=useState('All Blocks'),[q,setQ]=useState('');
 const [form,setForm]=useState({row:'',category:'Material',vendor:'',invoice:'',qty:'',rate:'',tax:'0',status:'Unpaid' as Expense['status']});
 useEffect(()=>{try{Promise.all([loadBoqData(),Promise.resolve(JSON.parse(localStorage.getItem(KEY)||'[]'))]).then(([r,e])=>{setRows(r);setExpenses(e)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load expenses')).finally(()=>setLoading(false))}catch(e){setError(e instanceof Error?e.message:'Unable to load expenses');setLoading(false)}},[]);
 const lots=useMemo(()=>Array.from(new Set(rows.map(r=>r.lot))).sort(),[rows]);
 const blocks=useMemo(()=>Array.from(new Set(rows.filter(r=>lot==='All Lots'||r.lot===lot).map(r=>r.block).filter(Boolean))).sort(),[rows,lot]);
 const items=useMemo(()=>rows.filter(r=>(lot==='All Lots'||r.lot===lot)&&(block==='All Blocks'||r.block===block)&&(!q||Object.values(r).join(' ').toLowerCase().includes(q.toLowerCase()))),[rows,lot,block,q]);
 const total=useMemo(()=>expenses.reduce((s,e)=>s+e.amount+e.tax,0),[expenses]),paid=useMemo(()=>expenses.filter(e=>e.status==='Paid').reduce((s,e)=>s+e.amount+e.tax,0),[expenses]);
 const byCategory=useMemo(()=>{const m=new Map<string,number>();expenses.forEach(e=>m.set(e.category,(m.get(e.category)||0)+e.amount+e.tax));return [...m.entries()].sort((a,b)=>b[1]-a[1])},[expenses]);
 const byLot=useMemo(()=>{const m=new Map<string,number>();expenses.forEach(e=>m.set(e.lot,(m.get(e.lot)||0)+e.amount+e.tax));return [...m.entries()].sort()},[expenses]);
 const add=()=>{const r=rows.find(x=>k(x)===form.row);if(!r||!form.vendor)return;const base=Math.max(0,Number(form.qty)||0)*Math.max(0,Number(form.rate)||0),tax=base*Math.max(0,Number(form.tax)||0)/100;const e:Expense={id:crypto.randomUUID(),date:new Date().toISOString().slice(0,10),lot:r.lot,block:r.block,scheme:r.schemeName,item:k(r),category:form.category,vendor:form.vendor,invoice:form.invoice,qty:Number(form.qty)||0,rate:Number(form.rate)||0,tax,amount:base,status:form.status};const next=[e,...expenses];setExpenses(next);localStorage.setItem(KEY,JSON.stringify(next));setForm({row:'',category:'Material',vendor:'',invoice:'',qty:'',rate:'',tax:'0',status:'Unpaid'})};
 if(loading)return <Shell><div className='content'><h1 className='title'>Expenses</h1><p className='muted'>Loading project cost register…</p></div></Shell>;
 if(error)return <Shell><div className='content'><h1 className='title'>Expenses error</h1><div className='card'>{error}</div></div></Shell>;
 const selection=expenses.filter(e=>(lot==='All Lots'||e.lot===lot)&&(block==='All Blocks'||e.block===block));
 const selectionTotal=selection.reduce((s,e)=>s+e.amount+e.tax,0);
 return <Shell><div className='content'><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h1 className='title'>Expenses & Cost Control</h1><p className='muted'>Capture actual project cost against Lot → Block → Scheme → Item for profitability and variance analysis.</p></div><Link className='btn secondary' href='/finance'>Project Finance</Link></div>
 <div className='grid grid4' style={{marginTop:18}}><div className='card'><div className='muted'>Expense records</div><div className='kpi'>{expenses.length}</div></div><div className='card'><div className='muted'>Total cost</div><div className='kpi'>{money(total)}</div></div><div className='card'><div className='muted'>Paid</div><div className='kpi'>{money(paid)}</div></div><div className='card'><div className='muted'>Outstanding</div><div className='kpi'>{money(total-paid)}</div></div></div>
 <div className='grid grid3' style={{marginTop:16}}><div className='card' style={{gridColumn:'span 2'}}><h3>New expense entry</h3><div className='form'><label>BOQ item<select className='input' value={form.row} onChange={e=>setForm({...form,row:e.target.value})}><option value=''>Select item</option>{items.slice(0,1000).map(r=><option key={k(r)} value={k(r)}>{r.itemCode} · {r.schemeName} · {r.itemDescription.slice(0,65)}</option>)}</select></label><div className='grid grid3'><label>Category<select className='input' value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Material</option><option>Labour</option><option>Plant & Machinery</option><option>Transport</option><option>Subcontract</option><option>Overhead</option><option>Other</option></select></label><label>Vendor / Payee<input className='input' value={form.vendor} onChange={e=>setForm({...form,vendor:e.target.value})}/></label><label>Invoice No.<input className='input' value={form.invoice} onChange={e=>setForm({...form,invoice:e.target.value})}/></label></div><div className='grid grid3'><label>Quantity<input className='input' type='number' min='0' step='any' value={form.qty} onChange={e=>setForm({...form,qty:e.target.value})}/></label><label>Rate<input className='input' type='number' min='0' step='any' value={form.rate} onChange={e=>setForm({...form,rate:e.target.value})}/></label><label>Tax %<input className='input' type='number' min='0' step='any' value={form.tax} onChange={e=>setForm({...form,tax:e.target.value})}/></label></div><button className='btn' onClick={add}>Add Expense</button></div></div><div className='card'><h3>Cost categories</h3>{byCategory.map(([c,v])=><div key={c} style={{marginTop:12}}><div style={{display:'flex',justifyContent:'space-between',fontSize:13}}><span>{c}</span><b>{money(v)}</b></div><div style={{height:8,background:'#e5e7eb',borderRadius:99,marginTop:5}}><div style={{height:'100%',width:(total?Math.min(100,v/total*100):0)+'%',background:'#2563eb',borderRadius:99}}/></div></div>)}{!byCategory.length&&<p className='muted'>No costs entered yet.</p>}</div></div>
 <div className='card' style={{marginTop:16}}><div className='toolbar'><select className='input' value={lot} onChange={e=>{setLot(e.target.value);setBlock('All Blocks')}}><option>All Lots</option>{lots.map(x=><option key={x}>{x}</option>)}</select><select className='input' value={block} onChange={e=>setBlock(e.target.value)}><option>All Blocks</option>{blocks.map(x=><option key={x}>{x}</option>)}</select><input className='input' style={{minWidth:300}} placeholder='Search BOQ item…' value={q} onChange={e=>setQ(e.target.value)}/></div></div>
 <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>Cost by Lot</h3><table className='table'><thead><tr><th>Lot</th><th>Actual Cost</th><th>Share</th></tr></thead><tbody>{byLot.map(([l,v])=><tr key={l}><td><b>{l}</b></td><td>{money(v)}</td><td>{(total?v/total*100:0).toFixed(1)}%</td></tr>)}</tbody></table></div>
 <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>Expense register</h3><p className='muted'>Current selection cost: {money(selectionTotal)}</p><table className='table'><thead><tr><th>Date</th><th>Lot</th><th>Block</th><th>Scheme</th><th>Category</th><th>Vendor</th><th>Invoice</th><th>Qty</th><th>Rate</th><th>Tax</th><th>Total</th><th>Status</th></tr></thead><tbody>{expenses.filter(e=>(lot==='All Lots'||e.lot===lot)&&(block==='All Blocks'||e.block===block)).map(e=><tr key={e.id}><td>{e.date}</td><td>{e.lot}</td><td>{e.block}</td><td>{e.scheme}</td><td>{e.category}</td><td><b>{e.vendor}</b></td><td>{e.invoice||'—'}</td><td>{qty(e.qty)}</td><td>{money(e.rate)}</td><td>{money(e.tax)}</td><td><b>{money(e.amount+e.tax)}</b></td><td><span className='badge'>{e.status}</span></td></tr>)}</tbody></table>{!expenses.length&&<p className='muted'>No expenses recorded yet.</p>}</div>
 </div></Shell>;
}
