'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import Shell from '@/components/Shell';
import {loadBoqData,type BoqRow} from '@/lib/boqData';
const KEY='projectos-execution-v2';
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN');
const qty=(n:number)=>n.toLocaleString('en-IN',{maximumFractionDigits:3});
const effectiveRate=(r:BoqRow)=>r.itemCode==='S001'?1:(typeof r.rate==='number'?r.rate:0);
const amount=(r:BoqRow,q:number)=>effectiveRate(r)*q;
export default function ExecutionPage(){
 const [rows,setRows]=useState<BoqRow[]>([]),[ex,setEx]=useState<Record<string,number>>({}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [lot,setLot]=useState('All Lots'),[block,setBlock]=useState('All Blocks'),[scheme,setScheme]=useState('All Schemes'),[search,setSearch]=useState('');
 useEffect(()=>{Promise.all([loadBoqData(),Promise.resolve(typeof window==='undefined'?{}:JSON.parse(localStorage.getItem(KEY)||'{}'))]).then(([r,e])=>{setRows(r);setEx(e)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load execution data')).finally(()=>setLoading(false))},[]);
 const key=(r:BoqRow)=>[r.lot,r.schemeId||'',r.schemeName,r.itemCode,r.itemDescription].join('|');
 const executed=(r:BoqRow)=>Math.min(r.approvedQty,Math.max(0,Number(ex[key(r)]||0)));
 const executionPct=(r:BoqRow)=>r.approvedQty?executed(r)/r.approvedQty*100:0;
 const lots=useMemo(()=>Array.from(new Set(rows.map(r=>r.lot))).sort(),[rows]);
 const blocks=useMemo(()=>Array.from(new Set(rows.filter(r=>lot==='All Lots'||r.lot===lot).map(r=>r.block).filter(Boolean))).sort(),[rows,lot]);
 const schemes=useMemo(()=>Array.from(new Set(rows.filter(r=>(lot==='All Lots'||r.lot===lot)&&(block==='All Blocks'||r.block===block)).map(r=>r.schemeName))).sort(),[rows,lot,block]);
 const filtered=useMemo(()=>rows.filter(r=>(lot==='All Lots'||r.lot===lot)&&(block==='All Blocks'||r.block===block)&&(scheme==='All Schemes'||r.schemeName===scheme)&&(!search||Object.values(r).join(' ').toLowerCase().includes(search.toLowerCase()))),[rows,lot,block,scheme,search]);
 const totals=useMemo(()=>filtered.reduce((a,r)=>{const e=executed(r);a.approvedQty+=r.approvedQty;a.executedQty+=e;a.approvedValue+=amount(r,r.approvedQty);a.executedValue+=amount(r,e);return a},{approvedQty:0,executedQty:0,approvedValue:0,executedValue:0}),[filtered,ex]);
 const schemeRows=useMemo(()=>{const m=new Map<string,{name:string;lot:string;block:string;approved:number;executed:number;value:number;execValue:number}>();filtered.forEach(r=>{const k=r.lot+'|'+r.schemeName;const x=m.get(k)||{name:r.schemeName,lot:r.lot,block:r.block,approved:0,executed:0,value:0,execValue:0};const e=executed(r);x.approved+=r.approvedQty;x.executed+=e;x.value+=amount(r,r.approvedQty);x.execValue+=amount(r,e);m.set(k,x)});return [...m.values()].sort((a,b)=>b.value-a.value)},[filtered,ex]);
 const save=(r:BoqRow,s:string)=>{const next={...ex,[key(r)]:Math.min(r.approvedQty,Math.max(0,Number(s)||0))};setEx(next);localStorage.setItem(KEY,JSON.stringify(next))};
 if(loading)return <Shell><div className='content'><h1 className='title'>Execution</h1><p className='muted'>Loading approved BOQ and execution register…</p></div></Shell>;
 if(error)return <Shell><div className='content'><h1 className='title'>Execution error</h1><div className='card'>{error}</div></div></Shell>;
 const pct=totals.approvedValue?totals.executedValue/totals.approvedValue*100:0;
 return <Shell><div className='content'><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h1 className='title'>Execution Control</h1><p className='muted'>Record actual site execution against approved BOQ quantities. Execution shows how much work is physically completed; billing is controlled later through measurement and RA Bills.</p></div><Link className='btn secondary' href='/measurements'>Continue to Measurements</Link></div>
 <div className='grid grid4' style={{marginTop:18}}><div className='card'><div className='muted'>Approved value</div><div className='kpi'>{money(totals.approvedValue)}</div></div><div className='card'><div className='muted'>Executed value</div><div className='kpi'>{money(totals.executedValue)}</div></div><div className='card'><div className='muted'>Balance value</div><div className='kpi'>{money(totals.approvedValue-totals.executedValue)}</div></div><div className='card'><div className='muted'>Execution progress</div><div className='kpi'>{pct.toFixed(1)}%</div><div className='muted' style={{fontSize:12}}>Value-based portfolio progress</div></div></div>
 <div className='card' style={{marginTop:16}}><div style={{display:'flex',justifyContent:'space-between'}}><h3>Overall execution progress</h3><b>{pct.toFixed(1)}%</b></div><div style={{height:14,background:'#e5e7eb',borderRadius:99,overflow:'hidden',marginTop:8}}><div style={{height:'100%',width:Math.min(100,pct)+'%',background:'#2563eb'}}/></div><p className='muted' style={{marginTop:8}}>Approved: {money(totals.approvedValue)} · Executed: {money(totals.executedValue)} · Balance: {money(totals.approvedValue-totals.executedValue)}</p></div>
 <div className='card' style={{marginTop:16}}><div className='toolbar'><select className='input' value={lot} onChange={e=>{setLot(e.target.value);setBlock('All Blocks');setScheme('All Schemes')}}><option>All Lots</option>{lots.map(x=><option key={x}>{x}</option>)}</select><select className='input' value={block} onChange={e=>{setBlock(e.target.value);setScheme('All Schemes')}}><option>All Blocks</option>{blocks.map(x=><option key={x}>{x}</option>)}</select><select className='input' value={scheme} onChange={e=>setScheme(e.target.value)}><option>All Schemes</option>{schemes.map(x=><option key={x}>{x}</option>)}</select><input className='input' style={{minWidth:280}} placeholder='Search item, scheme, code…' value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
 <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>Scheme execution summary</h3><table className='table'><thead><tr><th>Lot</th><th>Block</th><th>Scheme</th><th>Approved Qty</th><th>Executed Qty</th><th>Balance</th><th>Approved Value</th><th>Executed Value</th><th>Progress</th></tr></thead><tbody>{schemeRows.map(x=><tr key={x.lot+'|'+x.name}><td>{x.lot}</td><td>{x.block}</td><td><b>{x.name}</b></td><td>{qty(x.approved)}</td><td>{qty(x.executed)}</td><td>{qty(x.approved-x.executed)}</td><td>{money(x.value)}</td><td>{money(x.execValue)}</td><td style={{minWidth:130}}><div style={{fontSize:12,marginBottom:4}}>{(x.value?x.execValue/x.value*100:0).toFixed(1)}%</div><div style={{height:8,background:'#e5e7eb',borderRadius:99}}><div style={{height:'100%',width:Math.min(100,x.value?x.execValue/x.value*100:0)+'%',background:'#2563eb',borderRadius:99}}/></div></td></tr>)}</tbody></table></div>
 <div className='card' style={{marginTop:16,overflowX:'auto'}}><h3>Item execution register</h3><p className='muted'>Enter cumulative executed quantity. The item percentage is calculated as Executed Qty ÷ Approved Qty × 100. Execution does not create a bill amount.</p><table className='table'><thead><tr><th>Lot</th><th>Scheme</th><th>Item</th><th>Description</th><th>Unit</th><th>Rate</th><th>Approved</th><th>Executed</th><th>Execution %</th><th>Balance</th><th>Executed Value</th><th>Save</th></tr></thead><tbody>{filtered.slice(0,2000).map(r=>{const e=executed(r),ep=executionPct(r);return <tr key={key(r)}><td>{r.lot}</td><td>{r.schemeName}</td><td><b>{r.itemCode}</b></td><td style={{minWidth:360,whiteSpace:'pre-wrap'}}>{r.itemDescription}</td><td>{r.unit}</td><td>{r.itemCode==='S001'?money(1):typeof r.rate==='number'?money(r.rate):r.rate||'—'}</td><td>{qty(r.approvedQty)}</td><td><input className='input' style={{width:120}} type='number' min='0' max={r.approvedQty} step='any' value={e} onChange={ev=>save(r,ev.target.value)}/></td><td><b>{ep.toFixed(1)}%</b></td><td>{qty(r.approvedQty-e)}</td><td>{money(amount(r,e))}</td><td><span className='badge'>Saved</span></td></tr>})}</tbody></table>{filtered.length>2000&&<p className='muted'>Showing first 2,000 rows; narrow the filters to work with the remaining items.</p>}</div>
 </div></Shell>;
}
