'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import Shell from '@/components/Shell';
import {loadBoqData,type BoqRow} from '@/lib/boqData';
const EX='projectos-execution-v2',ME='projectos-measurements-v1',BILL='projectos-ra-bills-v1',PAY='projectos-payments-v1',EXP='projectos-expenses-v1';
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN');
const pct=(n:number)=>`${Math.max(0,Math.min(100,n)).toFixed(1)}%`;
const key=(r:BoqRow)=>[r.lot,r.schemeId||'',r.schemeName,r.itemCode,r.itemDescription].join('|');
const C={navy:'#17324d',blue:'#2563eb',teal:'#0f766e',green:'#15803d',amber:'#c47a08',red:'#c2410c'};
function Bar({v,max,c}:{v:number;max:number;c:string}){return <div style={{height:10,background:'#edf2f7',borderRadius:99,overflow:'hidden'}}><div style={{height:'100%',width:`${max?Math.min(100,v/max*100):0}%`,background:c,borderRadius:99}}/></div>}
export default function Dashboard(){
 const [rows,setRows]=useState<BoqRow[]>([]),[ex,setEx]=useState<Record<string,number>>({}),[meas,setMeas]=useState<Record<string,number>>({}),[bills,setBills]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[expenses,setExpenses]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{Promise.all([loadBoqData(),Promise.resolve(JSON.parse(localStorage.getItem(EX)||'{}')),Promise.resolve(JSON.parse(localStorage.getItem(ME)||'{}')),Promise.resolve(JSON.parse(localStorage.getItem(BILL)||'[]')),Promise.resolve(JSON.parse(localStorage.getItem(PAY)||'[]')),Promise.resolve(JSON.parse(localStorage.getItem(EXP)||'[]'))]).then(([r,x,m,b,p,e])=>{setRows(r);setEx(x);setMeas(m);setBills(b);setPayments(p);setExpenses(e)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load dashboard')).finally(()=>setLoading(false))},[]);
 const lots=useMemo(()=>Array.from(new Set(rows.map(r=>r.lot))).sort(),[rows]);
 const stats=useMemo(()=>lots.map(l=>{const rr=rows.filter(r=>r.lot===l);const approved=rr.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*r.approvedQty:0),0);const executed=rr.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*Math.min(r.approvedQty,Number(ex[key(r)]||0)):0),0);const measured=rr.reduce((s,r)=>s+(typeof r.rate==='number'?r.rate*Math.min(Math.min(r.approvedQty,Number(ex[key(r)]||0)),Number(meas[key(r)]||0)):0),0);const billed=bills.filter(b=>b.lot===l).reduce((s,b)=>s+Number(b.grandTotal||0),0);const cost=expenses.filter(e=>e.lot===l).reduce((s,e)=>s+Number(e.amount||0)+Number(e.tax||0),0);return {lot:l,approved,executed,measured,billed,cost,progress:approved?executed/approved*100:0}}),[lots,rows,ex,meas,bills,expenses]);
 const total=stats.reduce((a,s)=>({approved:a.approved+s.approved,executed:a.executed+s.executed,measured:a.measured+s.measured,billed:a.billed+s.billed,cost:a.cost+s.cost}),{approved:0,executed:0,measured:0,billed:0,cost:0});
 const paid=payments.filter(p=>p.status==='Paid').reduce((s,p)=>s+Number(p.amount||0),0);
 const top=useMemo(()=>{const m=new Map<string,{name:string;lot:string;approved:number;executed:number}>();rows.forEach(r=>{const id=r.lot+'|'+r.schemeName;const s=m.get(id)||{name:r.schemeName,lot:r.lot,approved:0,executed:0};if(typeof r.rate==='number'){s.approved+=r.rate*r.approvedQty;s.executed+=r.rate*Math.min(r.approvedQty,Number(ex[key(r)]||0))}m.set(id,s)});return [...m.values()].sort((a,b)=>b.approved-a.approved).slice(0,6)},[rows,ex]);
 if(loading)return <Shell><div className='content'><h1 className='title'>HQ Control Dashboard</h1><p className='muted'>Loading live project controls…</p></div></Shell>;
 if(error)return <Shell><div className='content'><h1 className='title'>HQ Control Dashboard</h1><div className='card'>{error}</div></div></Shell>;
 const health=[['Execution',total.executed,total.approved,C.blue],['Measurement',total.measured,total.executed,C.teal],['Billing',total.billed,total.executed,C.amber],['Collection',paid,total.billed,C.green]] as [string,number,number,string][];
 return <Shell><div className='content'>
 <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:15,flexWrap:'wrap'}}><div><div className='muted' style={{fontSize:12,fontWeight:800,letterSpacing:'.08em'}}>HQ PROJECT CONTROL</div><h1 className='title' style={{margin:'4px 0'}}>Sant Kabir Nagar Rural Water Supply Project</h1><p className='muted'>Live portfolio view across approved BOQ, execution, measurements, billing and entered costs.</p></div><Link className='btn' href='/reports'>Open Management Reports</Link></div>
 <div className='grid grid4' style={{marginTop:20}}>{[['Approved Value',total.approved,C.navy,'BOQ baseline'],['Executed Value',total.executed,C.blue,pct(total.approved?total.executed/total.approved*100:0)+' of approved'],['Billed Value',total.billed,C.amber,pct(total.executed?total.billed/total.executed*100:0)+' of executed'],['Actual Cost',total.cost,C.red,'Entered expenses']].map(([l,v,c,s])=><div className='card' key={String(l)} style={{borderTop:`3px solid ${String(c)}`}}><div className='muted'>{l}</div><div className='kpi'>{money(Number(v))}</div><div className='muted' style={{fontSize:12}}>{s}</div></div>)}</div>
 <div className='grid grid2' style={{marginTop:18}}><div className='card'><h3 style={{margin:0}}>Portfolio execution</h3><p className='muted' style={{fontSize:12}}>Lot-wise approved value versus executed value.</p>{stats.map(s=><div key={s.lot} style={{margin:'17px 0'}}><div style={{display:'flex',justifyContent:'space-between',fontSize:13,marginBottom:6}}><b>{s.lot}</b><span>{pct(s.progress)}</span></div><Bar v={s.executed} max={s.approved} c={C.blue}/><div className='muted' style={{fontSize:11,marginTop:5}}>{money(s.executed)} / {money(s.approved)}</div></div>)}</div>
 <div className='card'><h3 style={{margin:0}}>Cash & delivery health</h3><p className='muted' style={{fontSize:12}}>The control ratios an HQ reviewer should see first.</p>{health.map(([l,v,m,c])=><div key={l} style={{margin:'17px 0'}}><div style={{display:'flex',justifyContent:'space-between',fontSize:13,marginBottom:6}}><span>{l}</span><b>{pct(m?v/m*100:0)}</b></div><Bar v={v} max={m} c={c}/></div>)}<div style={{display:'flex',justifyContent:'space-between',borderTop:'1px solid #e7edf3',paddingTop:13,fontSize:13}}><span>Receivable</span><b>{money(Math.max(0,total.billed-paid))}</b></div></div></div>
 <div className='card' style={{marginTop:18,overflowX:'auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h3 style={{margin:0}}>Lot control register</h3><p className='muted' style={{fontSize:12}}>One view of physical and financial position.</p></div><Link className='btn secondary' href='/lots'>Open Lots</Link></div><table className='table'><thead><tr><th>Lot</th><th>Approved</th><th>Executed</th><th>Measured</th><th>Billed</th><th>Cost</th><th>Progress</th></tr></thead><tbody>{stats.map(s=><tr key={s.lot}><td><b>{s.lot}</b></td><td>{money(s.approved)}</td><td>{money(s.executed)}</td><td>{money(s.measured)}</td><td>{money(s.billed)}</td><td>{money(s.cost)}</td><td style={{minWidth:170}}><div style={{display:'grid',gridTemplateColumns:'52px 1fr',gap:8,alignItems:'center'}}><b>{pct(s.progress)}</b><Bar v={s.progress} max={100} c={s.progress>=75?C.green:s.progress>=40?C.blue:C.amber}/></div></td></tr>)}</tbody></table></div>
 <div className='card' style={{marginTop:18,overflowX:'auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h3 style={{margin:0}}>Largest schemes</h3><p className='muted'>Highest approved-value schemes and current execution.</p></div><Link className='btn secondary' href='/schemes'>Scheme Register</Link></div><table className='table'><thead><tr><th>Lot</th><th>Scheme</th><th>Approved</th><th>Executed</th><th>Progress</th></tr></thead><tbody>{top.map(s=><tr key={s.lot+'|'+s.name}><td>{s.lot}</td><td style={{minWidth:280}}><b>{s.name}</b></td><td>{money(s.approved)}</td><td>{money(s.executed)}</td><td>{pct(s.approved?s.executed/s.approved*100:0)}</td></tr>)}</tbody></table></div>
 <div className='grid grid4' style={{marginTop:18}}>{[['BOQ Control','Review lots, schemes, items and quantities.','/boq'],['Execution','Update physical execution against approved BOQ.','/execution'],['Finance','Compare value, billing, cost and collection.','/finance'],['Reports','Management charts and exportable analysis.','/reports']].map(([t,d,h])=><Link key={String(t)} href={String(h)} className='card' style={{textDecoration:'none',color:'inherit'}}><h3 style={{margin:'0 0 5px'}}>{t}</h3><p className='muted' style={{fontSize:12,margin:0}}>{d}</p></Link>)}</div>
 <div className='muted' style={{fontSize:11,marginTop:14}}>Dashboard values are derived from the shared BOQ and recorded browser transactions. No missing execution, billing or cost values are estimated.</div>
 </div></Shell>;
}
